#!/usr/bin/env python3
"""Top-up observations: 10 new posts each for 6 short accounts → 25 total each."""
import json, pathlib, time, random, datetime

CROCKFORD = '0123456789ABCDEFGHJKMNPQRSTVWXYZ'
REPO = pathlib.Path('/Users/abarihm/Desktop/ogz-knowledge')

def make_ulid():
    ts = int(time.time() * 1000)
    ts_part = ''
    t = ts
    for _ in range(10):
        ts_part = CROCKFORD[t % 32] + ts_part
        t //= 32
    rand_part = ''.join(random.choice(CROCKFORD) for _ in range(16))
    time.sleep(0.003)
    return ts_part + rand_part

def obs(account_norm, account_ulid, sector, shortcode, content_type, capture_date,
        composition, lighting, colors, props, setting, chars, overlays, notable,
        lang, dialect, register, tone, cta, hashtags, caption,
        hard_blocks, soft_flags, compliance,
        region, occasion, patterns, hosp_cues,
        prod_quality, brand_consistency, engagement_potential,
        source_suffix=''):
    fn_ext = '_thumb.jpg' if content_type in ('video','reel') else '.jpg'
    return {
        'observation_ulid': make_ulid(),
        'schema_version': 1,
        'account_handle_normalized': account_norm,
        'account_ulid': account_ulid,
        'sector': sector,
        'content_ref': {
            'filename': shortcode + fn_ext,
            'platform': 'instagram',
            'content_type': content_type,
            'capture_date': capture_date,
            'source_url': f'https://www.instagram.com/p/{shortcode}/',
        },
        'visual_observations': {
            'composition_style': composition,
            'lighting': lighting,
            'color_palette_dominant': colors,
            'props_visible': props,
            'setting': setting,
            'characters_visible': {'count': chars},
            'text_overlays': overlays,
            'notable_visual_elements': notable,
        },
        'voice_observations': {
            'language': lang,
            'dialect_detected': dialect,
            'register': register,
            'tone': tone,
            'notable_phrases': [],
            'call_to_action_present': cta,
        },
        'compliance_check': {
            'hard_blocks_triggered': hard_blocks,
            'soft_flags': soft_flags,
            'overall_compliance': compliance,
        },
        'cultural_notes': {
            'regional_orientation_detected': region,
            'occasion_relevance': occasion,
            'hospitality_cues': hosp_cues,
        },
        'pattern_matches': [{'pattern_slug': p, 'confidence': 'moderate', 'notes': None} for p in patterns],
        'quality_assessment': {
            'production_quality': prod_quality,
            'brand_consistency_with_account': brand_consistency,
            'engagement_potential': engagement_potential,
        },
        'provenance': {
            'source': f'benchmark:@{source_suffix}; content:{shortcode}{fn_ext}',
            'date_added': datetime.datetime.utcnow().isoformat() + 'Z',
            'confirmer': 'claude_code_extraction',
            'confidence': 'inferred',
            'scope': f'sector:{sector}',
        },
    }

ALL_OBS = []

# ── @herfyfsc ─────────────────────────────────────────────────────────────────
# NEW: PowerPuff Girls campaign + Ramadan فوازير
NORM_H = 'OGZ-F-AND-B-Reference-006'
ULID_H = '01KS8MQHR0SVWGFRK2NDA3YT6P'

ALL_OBS += [
obs(NORM_H, ULID_H, 'f_and_b', 'DYcBJmAlPPa', 'video', '2026-05-15',
    'split screen collab reveal', 'vibrant pop art bright', ['pink','blue','green','white'],
    ['powerpuff girls IP artwork','herfy branded meal box','colourful sauce trio'],
    'animated brand collab graphic', 0,
    [{'language':'arabic','content_summary':'PowerPuff Girls collab campaign launch'}],
    ['highest-engagement post in new PPG campaign — 1504 likes'],
    'arabic','najdi','casual','excited', True, ['#وجبة_فتيات_القوة','#هرفي'],
    'وجبة فتيات القوة مع صوصات وفيقرز لكل شخصية ألذ وجبة وألطف تفاصيل',
    [], [], 'clean', 'general_saudi', 'none',
    ['seasonal_collection_drop','product_hero','behind_the_craft'], [],
    'professional', 'strong', 'high', 'herfyfsc'),

obs(NORM_H, ULID_H, 'f_and_b', 'DYcCtYvDd3L', 'video', '2026-05-15',
    'product hero trio flat lay', 'bright studio overhead', ['red','blue','green','yellow','white'],
    ['3 coloured sauces PPG themed','fries box branded','10 SAR price badge'],
    'studio product shot themed collab', 0,
    [{'language':'arabic','content_summary':'3 PPG character sauces promo 10 SAR'}],
    ['price callout 10 SAR — low price accessibility mechanic'],
    'arabic','najdi','casual','playful', True, ['#وجبة_فتيات_القوة'],
    'بطاطس بثلاث صوصات مستوحاة من فتيات القوة ب 10 ريال بس',
    [], [], 'clean', 'general_saudi', 'none',
    ['seasonal_collection_drop','product_hero','invitation_to_witness'],
    [], 'professional', 'strong', 'high', 'herfyfsc'),

obs(NORM_H, ULID_H, 'f_and_b', 'DYZF1OSCpQo', 'video', '2026-05-13',
    'mystery teaser motion graphic', 'dramatic dark contrast', ['deep_red','electric_blue','green'],
    ['colour explosion graphic','mystery potion reveal animation'],
    'animated branded teaser', 0,
    [{'language':'arabic','content_summary':'sugar spice everything nice teaser — PPG origin story'}],
    ['classic PPG origin story hook for Saudi audience — pre-launch tease'],
    'arabic','najdi','casual','mysterious', False, ['#هرفي','#Herfy'],
    'سكّر، بهار، وكل ما هو لذيذ — عرفتوا الجاي؟',
    [], [], 'clean', 'general_saudi', 'none',
    ['seasonal_collection_drop','specific_emotional_state','behind_the_craft'],
    [], 'professional', 'strong', 'high', 'herfyfsc'),

obs(NORM_H, ULID_H, 'f_and_b', 'DYewDs4jfcA', 'carousel_slide', '2026-05-14',
    'mood carousel swipe sequence', 'warm lifestyle', ['orange','pink','teal'],
    ['PPG meal box','lifestyle before-after','customer smiling'],
    'lifestyle relatable carousel', 1,
    [{'language':'arabic','content_summary':'PPG meal fixed my mood — carousel story'}],
    ['mood-fix narrative — strongest engagement mechanic in new campaign (454 likes)'],
    'arabic','najdi','casual','warm', False, ['#وجبة_فتيات_القوة','#هرفي'],
    'وجبة فتيات القوه كانت كفيلة بتعديل المّود',
    [], [], 'clean', 'general_saudi', 'none',
    ['customer_voice_ugc','specific_emotional_state','invitation_to_witness'],
    [], 'professional', 'strong', 'high', 'herfyfsc'),

obs(NORM_H, ULID_H, 'f_and_b', 'DYXaQk6mFWD', 'video', '2026-05-12',
    'dramatic countdown teaser', 'high contrast dark', ['black','neon_green','white'],
    ['power lightning graphic','countdown clock animation'],
    'pre-launch motion teaser', 0,
    [{'language':'arabic','content_summary':'Power is coming — campaign pre-launch teaser'}],
    ['189 likes on pure teaser — strong anticipation-build for Saudi F&B audience'],
    'arabic','najdi','casual','anticipatory', False, ['#هرفي','#Herfy'],
    'جهّزوا نفسكم للمفاجأة اللطيفة — القوّه قربت',
    [], [], 'clean', 'general_saudi', 'none',
    ['seasonal_collection_drop','specific_emotional_state'],
    [], 'professional', 'strong', 'medium', 'herfyfsc'),

obs(NORM_H, ULID_H, 'f_and_b', 'DYkHkm6kl4M', 'video', '2026-05-18',
    'character trio split screen', 'bright pop', ['pink','blue','green'],
    ['Blossom character card','Bubbles character card','Buttercup card'],
    'PPG character identity quiz', 0,
    [{'language':'arabic','content_summary':'Which PPG character are you? personality poll'}],
    ['personality alignment mechanic — same formula as herfyfsc Spacetoon character quizzes'],
    'arabic','najdi','casual','playful', False, ['#وجبة_فتيات_القوة'],
    'ثلاث شخصيات وثلاث طاقات مختلفة — مين الأقرب لشخصيتك؟',
    [], [], 'clean', 'general_saudi', 'none',
    ['gamified_content','personality_food_pairing','seasonal_collection_drop'],
    [], 'professional', 'strong', 'medium', 'herfyfsc'),

obs(NORM_H, ULID_H, 'f_and_b', 'DYhSno-gTR4', 'image', '2026-05-19',
    'character POV product reveal', 'lab bright fluorescent', ['green','white','blue'],
    ['Professor Utonium character graphic','secret recipe scroll prop','branded meal'],
    'IP storytelling product reveal', 0,
    [{'language':'arabic','content_summary':'Professor reveals secret recipe — fries campaign'}],
    ['narrative IP hook — Professor character as brand storyteller for Saudi youth'],
    'arabic','najdi','casual','humorous', False, ['#وجبة_فتيات_القوة','#هرفي'],
    'البروفيسور أخيرًا طلع بالوصفة السرّية — ونتيجتها ألذ بطاطس ممكن تجربها',
    [], [], 'clean', 'general_saudi', 'none',
    ['behind_the_craft','seasonal_collection_drop','specific_dish_naming'],
    [], 'professional', 'strong', 'medium', 'herfyfsc'),

obs(NORM_H, ULID_H, 'f_and_b', 'DYUlT9tGjXG', 'image', '2026-05-11',
    'product farewell urgency shot', 'warm golden', ['orange','golden_brown','white'],
    ['Spacetoon meal box','limited time badge','countdown urgency text'],
    'limited time farewell product shot', 0,
    [{'language':'arabic','content_summary':'Last days of Spacetoon meal — try it before it leaves'}],
    ['farewell urgency mechanic bridges Spacetoon → PPG campaign transition'],
    'arabic','najdi','casual','urgent', True, ['#وجبة_شباب_المستقبل','#هرفي'],
    'أيام قليلة وتودّعنا وجبة شباب المستقبل جرّبها قبل تروح',
    [], [], 'clean', 'general_saudi', 'none',
    ['seasonal_collection_drop','invitation_to_witness'],
    [], 'professional', 'strong', 'medium', 'herfyfsc'),

obs(NORM_H, ULID_H, 'f_and_b', 'DYmV1F2mYE5', 'image', '2026-05-20',
    'product with emotional tagline', 'warm bright clean', ['pink','white','branded_orange'],
    ['PPG meal box','heart illustration','brand logo'],
    'product hero emotional statement', 0,
    [{'language':'arabic','content_summary':'PPG meal knocks on your heart directly — product hero'}],
    ['Saudi poetic device: meal "knocks on heart not door" — عاطفي food positioning'],
    'arabic','najdi','casual','warm', False, ['#وجبة_فتيات_القوة','#هرفي'],
    'وجبة فتيات القوة ما تدق بابك تدق على قلبك مباشرة',
    [], [], 'clean', 'general_saudi', 'none',
    ['product_hero','classical_arabic_warmth'],
    [], 'professional', 'strong', 'low', 'herfyfsc'),

obs(NORM_H, ULID_H, 'f_and_b', 'DHOdUpGtpNK', 'image', '2025-03-01',
    'branded riddle card flat lay', 'warm ramadan amber', ['purple','gold','cream'],
    ['Ramadan lantern motif','riddle text card','branded meal'],
    'Ramadan themed engagement series', 0,
    [{'language':'arabic','content_summary':'Baba Harfan riddles Ramadan series — answer for prize'}],
    ['#فوازير_بابا_هرفان Ramadan riddle series — seasonal occasion mechanic'],
    'arabic','najdi','casual','playful', True, ['#فوازير_بابا_هرفان','#هرفي'],
    'فوازير بابا هرفان ويقول وش فطورنا اليوم؟',
    [], [], 'clean', 'general_saudi', 'ramadan',
    ['ramadan_iftar_warmth','gamified_content','seasonal_collection_drop'],
    [], 'professional', 'strong', 'medium', 'herfyfsc'),
]

# ── @kuduksa ───────────────────────────────────────────────────────────────────
NORM_K = 'OGZ-F-AND-B-Reference-007'
ULID_K = '01KS5PYQ88T5AAR9PTC4NEWMPQ'

ALL_OBS += [
obs(NORM_K, ULID_K, 'f_and_b', 'DJJzbe6sszd', 'video', '2025-04-10',
    'prize reveal dramatic motion', 'high contrast bright', ['blue','gold','white'],
    ['Ford Territory car graphic','giveaway prize badge','Kudu brand logo'],
    'major giveaway prize reveal', 0,
    [{'language':'arabic','content_summary':'Historic moment — win Ford Territory + enter big prize draw'}],
    ['2242 likes — biggest engagement post in set; car giveaway mechanic drives huge participation'],
    'arabic','najdi','casual','excited', True, ['#كودو'],
    'لحظة للتاريخ! فرصتك تربح فورد تيروتري وتدخل السحب على أكبر جائزة',
    [], [], 'clean', 'general_saudi', 'none',
    ['seasonal_collection_drop','invitation_to_witness','gamified_content'],
    [], 'professional', 'strong', 'high', 'kuduksa'),

obs(NORM_K, ULID_K, 'f_and_b', 'DI8ll3BuJlP', 'video', '2025-03-28',
    'tutorial explainer POV', 'warm bright', ['blue','orange','white'],
    ['scratch card prop','employee Saleh spokesperson','prize layers graphic'],
    'employee tutorial spokesperson video', 1,
    [{'language':'arabic','content_summary':'Saleh explains how to enter Kudu prizes — scratch card mechanic'}],
    ['2185 likes — employee-as-explainer trust format; Saudi mechanic: scratch + win + layered prizes'],
    'arabic','najdi','casual','informative', True, ['#كودو'],
    'صالح يشرح كيف تدخلون السحب على جوائز كودو كل اللي عليك تكشط البطاقة',
    [], [], 'clean', 'general_saudi', 'none',
    ['educational_explainer','behind_the_craft','customer_voice_ugc'],
    [], 'professional', 'strong', 'high', 'kuduksa'),

obs(NORM_K, ULID_K, 'f_and_b', 'DI1FEFLAjmI', 'video', '2025-03-20',
    'event on-ground lifestyle', 'outdoor bright natural', ['blue','orange','green'],
    ['Spacetoon AlBomb stage setup','Qassim crowd','Kudu branded booth'],
    'live brand activation event coverage', 2,
    [{'language':'arabic','content_summary':'Kudu AlBomb surprises continue in Qassim — live tour event'}],
    ['Regional tour reach — Spacetoon nostalgia resonates across KSA cities beyond Riyadh'],
    'arabic','najdi','casual','energetic', False, ['#كودو_شباب_البومب'],
    'الحماس ما يوقّف شباب البومب وصلوا القصيم والمفاجآت مع كودو مستمرة',
    [], [], 'clean', 'central_saudi', 'none',
    ['behind_the_craft','customer_voice_ugc','warm_golden_hour_hero'],
    [], 'professional', 'strong', 'high', 'kuduksa'),

obs(NORM_K, ULID_K, 'f_and_b', 'DI_Fxw5Mm3C', 'video', '2025-03-30',
    'winners announcement celebration', 'bright festive', ['blue','gold','white'],
    ['iPhone 16 product shot','winners names/avatars','confetti graphic'],
    'branded winners celebration announcement', 0,
    [{'language':'arabic','content_summary':'iPhone 16 winners announced — giveaway continues for others'}],
    ['455 likes — winners post sustains participation by showing real prizes won'],
    'arabic','najdi','casual','celebratory', True, ['#كودو'],
    'ألف مبروك للفايزين بـ آيفون 16 ولقاءنا القريب لأكبر جائزة',
    [], [], 'clean', 'general_saudi', 'none',
    ['seasonal_collection_drop','invitation_to_witness'],
    [], 'professional', 'strong', 'high', 'kuduksa'),

obs(NORM_K, ULID_K, 'f_and_b', 'DJEMjK7NH0p', 'video', '2025-04-15',
    'collab teaser motion', 'dynamic pop', ['blue','orange','yellow'],
    ['Spacetoon AlBomb logo','Kudu logo','animated collab lockup'],
    'collab brand announcement', 0,
    [{'language':'arabic','content_summary':'Kudu Spacetoon AlBomb collab official announcement'}],
    ['369 likes on simple collab logo lockup — brand equity of Spacetoon in Saudi market'],
    'arabic','najdi','casual','excited', False, ['#كودو_شباب_البومب','#Kudu_Shabab_ElBomb'],
    'كودو شباب البومب',
    [], [], 'clean', 'general_saudi', 'none',
    ['seasonal_collection_drop','color_block_branded_flood'],
    [], 'professional', 'strong', 'high', 'kuduksa'),

obs(NORM_K, ULID_K, 'f_and_b', 'DIzDbZXp2T8', 'video', '2025-03-18',
    'brand loyalty warm hero', 'warm amber golden', ['blue','orange','cream'],
    ['family meal table','brand logo','loyalty tagline overlay'],
    'brand loyalty statement video', 2,
    [{'language':'arabic','content_summary':'Loyalty is on us — brand values warmth video'}],
    ['"الوفا علينا" — loyalty positioning, warm family brand identity anchor'],
    'arabic','najdi','casual','warm', False, ['#كودو'],
    'الوفا علينا',
    [], [], 'clean', 'general_saudi', 'none',
    ['warm_golden_hour_hero','classical_arabic_warmth','warm_najdi_invitational'],
    [], 'professional', 'strong', 'medium', 'kuduksa'),

obs(NORM_K, ULID_K, 'f_and_b', 'DJHc3VuBMQe', 'video', '2025-04-08',
    'product combo value reveal', 'bright clean', ['blue','orange','white'],
    ['burger combo meal','value price badge','happy weekend graphic'],
    'weekend value offer product shot', 0,
    [{'language':'arabic','content_summary':'Weekend offer — chicken burger combo large + 2 drinks offer'}],
    ['Weekend daypart activation — aligns with Thursday/Friday Saudi weekend pattern'],
    'arabic','najdi','casual','friendly', True, ['#كودو'],
    'جايينكم بعرض الوييييكند السعيد وجبة برجر دجاج كومبو العادية مع عروض',
    [], [], 'clean', 'general_saudi', 'none',
    ['product_hero','invitation_to_witness','seasonal_collection_drop'],
    [], 'professional', 'strong', 'medium', 'kuduksa'),

obs(NORM_K, ULID_K, 'f_and_b', 'DI4F0zJssUN', 'video', '2025-03-22',
    'product hero gaming lifestyle', 'dark gaming aesthetic', ['navy','neon_orange','white'],
    ['gaming controller prop','energy drink stylized','Kudu gaming menu box'],
    'gaming lifestyle product integration', 1,
    [{'language':'arabic','content_summary':'Gamers menu — energy + taste for long gaming sessions'}],
    ['Gamers menu daypart — KSA gaming culture is significant; positioned as late-night snack'],
    'arabic','najdi','casual','energetic', True, ['#كودو'],
    'طاقة تحفّزك وطعم يشبعك اطلبه من منيو القيمرز من كودو',
    [], [], 'clean', 'general_saudi', 'none',
    ['product_hero','lifestyle_embed','seasonal_collection_drop'],
    [], 'professional', 'strong', 'medium', 'kuduksa'),

obs(NORM_K, ULID_K, 'f_and_b', 'DJMfheeBywF', 'video', '2025-04-18',
    'brand presence everywhere montage', 'warm bright', ['blue','orange','green_saudi'],
    ['multiple city locations montage','brand logo overlay','tagline text'],
    'brand ubiquity statement video', 0,
    [{'language':'arabic','content_summary':'Kudu with you every moment every day — brand presence'}],
    ['"كودو معك في كل لحظة وكل يوم" — brand ubiquity claim across KSA'],
    'arabic','najdi','casual','warm', False, ['#كودو_من_ربعك'],
    'كودو معك في كل لحظة وكل يوم كودو من ربعك',
    [], [], 'clean', 'general_saudi', 'none',
    ['warm_najdi_invitational','classical_arabic_warmth','color_block_branded_flood'],
    [], 'professional', 'strong', 'medium', 'kuduksa'),

obs(NORM_K, ULID_K, 'f_and_b', 'DJGpA6APMf-', 'image', '2025-04-12',
    'family lifestyle weekend moment', 'warm golden hour natural', ['orange','cream','green'],
    ['family outdoor setting','Kudu meal bag','kids playing'],
    'family weekend lifestyle shot', 3,
    [{'language':'arabic','content_summary':'Kids happy, food amazing, atmosphere perfect — weekend plan?'}],
    ['Weekend family meal positioning — Thursday evening Saudi family outing culture'],
    'arabic','najdi','casual','warm', False, ['#كودو'],
    'الأكل رهيب والعيال مبسوطين والجو فلّة — وانت وش كانت خطتك بالويكند؟',
    [], [], 'clean', 'general_saudi', 'none',
    ['warm_golden_hour_hero','customer_voice_ugc','invitation_to_witness'],
    [], 'semi_professional', 'strong', 'medium', 'kuduksa'),
]

# ── @albaik ────────────────────────────────────────────────────────────────────
NORM_A = 'OGZ-F-AND-B-Reference-008'
ULID_A = '01KS5PZ5T50CY91R45QE57BT7P'

ALL_OBS += [
obs(NORM_A, ULID_A, 'f_and_b', 'DESKoJOtKHM', 'image', '2024-10-18',
    'product hero national pride', 'clean white studio', ['white','red_saudi','gold'],
    ['raw chicken pieces on Saudi flag themed surface','100% local badge','صنع في السعودية stamp'],
    'studio product shot with national pride framing', 0,
    [{'language':'arabic','content_summary':'AlBaik chicken 100% local Saudi — Made in Saudi Arabia'}],
    ['8151 likes — 2nd highest in set; Saudi-local sourcing as top brand value. National pride + food quality fused'],
    'arabic','hejazi','formal','proud', False, ['#البيك','#صنع_في_السعودية','#محلي١٠٠٪'],
    'من خيرات مملكتنا الغالية قطع دجاج البيك محلي ١٠٠٪ صنع في السعودية',
    [], [], 'clean', 'general_saudi', 'none',
    ['product_hero','national_day_pride','national_day_modernity_heritage'],
    [], 'professional', 'strong', 'high', 'albaik'),

obs(NORM_A, ULID_A, 'f_and_b', 'DDMYO6oI9SR', 'image', '2024-09-01',
    'product bundle overhead flat lay', 'warm studio', ['golden_brown','white','red'],
    ['fillet burger','strips bakes','side dish','full meal spread'],
    'complete meal bundle hero shot', 0,
    [{'language':'arabic','content_summary':'Chicken fillet burger + strips bakes + side — full experience'}],
    ['2737 likes — product bundle creates premium perception; "عيش التجربة بطريقتك" personalization framing'],
    'arabic','hejazi','casual','inviting', True, ['#البيك'],
    'عيش التجربة بطريقتك تمتع ببرجر فيليه الدجاج بالجبن مع ستربس بيكيز اللذيذة',
    [], [], 'clean', 'general_saudi', 'none',
    ['product_hero','overhead_tabletop_spread','specific_dish_naming'],
    [], 'professional', 'strong', 'high', 'albaik'),

obs(NORM_A, ULID_A, 'f_and_b', 'DGoP-afIJfc', 'image', '2025-03-08',
    'prayer time service announcement', 'clean minimal', ['white','green_saudi','gold'],
    ['prayer time indicator graphic','AlBaik logo','serving hours text'],
    'Ramadan prayer time service post', 0,
    [{'language':'arabic','content_summary':'Ramadan — serving from after Asr prayer; Eid Mubarak'}],
    ['Prayer-time service anchoring during Ramadan — unique to AlBaik brand positioning in KSA'],
    'arabic','hejazi','formal','respectful', False, ['#البيك'],
    'مبارك عليكم الشهر نسعد بخدمتكم من بعد صلاة العصر',
    [], [], 'clean', 'general_saudi', 'ramadan',
    ['ramadan_iftar_warmth','static_lockedoff_motion_inside','warm_najdi_invitational'],
    [], 'professional', 'strong', 'high', 'albaik'),

obs(NORM_A, ULID_A, 'f_and_b', 'DARXS4GICq2', 'video', '2024-09-23',
    'national day motion graphic', 'green gold white', ['saudi_green','gold','white'],
    ['Saudi flag waving','national day 94 badge','AlBaik logo'],
    'Saudi National Day branded motion', 0,
    [{'language':'arabic','content_summary':'Saudi National Day 94 — we dream and we achieve together'}],
    ['2247 likes — National Day content is mandatory for Saudi brands; minimal copy, flag + brand = formula'],
    'arabic','hejazi','formal','patriotic', False, ['#اليوم_الوطني_السعودي_94','#نحلم_ونحقق','#البيك'],
    'اليوم الوطني السعودي 94 حب يجمعنا نحلم ونحقق',
    [], [], 'clean', 'general_saudi', 'national_day',
    ['national_day_pride','national_day_modernity_heritage','color_block_branded_flood'],
    [], 'professional', 'strong', 'high', 'albaik'),

obs(NORM_A, ULID_A, 'f_and_b', 'DGlu_wTPDat', 'video', '2025-02-10',
    'product close up sizzle reel', 'warm studio', ['golden_brown','white','lemon'],
    ['fish fillet crispy shot','steam rising','branded paper wrap'],
    'new product sizzle video', 0,
    [{'language':'arabic','content_summary':'Fish fillet AlBaik — crispy tender unique experience'}],
    ['1683 likes — fish product launch; AlBaik diversifying from chicken; "تجربة فريدة" uniqueness hook'],
    'arabic','hejazi','casual','enticing', True, ['#البيك','#السمك'],
    'وجبة فيليه السمك من البيك تجربة فريدة تجمع بين القرمشة والطراوة والنكهة المميزة',
    [], [], 'clean', 'general_saudi', 'none',
    ['product_hero','close_up_macro_texture','seasonal_collection_drop'],
    [], 'professional', 'strong', 'high', 'albaik'),

obs(NORM_A, ULID_A, 'f_and_b', 'DDcf4juINp6', 'image', '2024-09-29',
    'national milestone celebration minimal', 'clean white gold', ['green','gold','white'],
    ['Expo 2030 logo','AlBaik logo','congratulation graphic'],
    'national milestone brand congratulation', 0,
    [{'language':'arabic','content_summary':'AlBaik congratulates Saudi Arabia on Expo 2030 win'}],
    ['1003 likes — Expo 2030 win as shared national pride moment; brand as citizen of Saudi identity'],
    'arabic','hejazi','formal','proud', False, ['#البيك'],
    'نبارك للوطن الغالي وقيادتنا الرشيدة والشعب السعودي الكريم هذا الإنجاز التاريخي',
    [], [], 'clean', 'general_saudi', 'none',
    ['national_day_pride','national_day_modernity_heritage','color_block_branded_flood'],
    [], 'professional', 'strong', 'high', 'albaik'),

obs(NORM_A, ULID_A, 'f_and_b', 'DAMUHbmII_6', 'carousel_slide', '2024-09-05',
    'product range carousel swipe', 'bright clean', ['golden_brown','white','red'],
    ['multiple AlBaik products','meal options carousel','branded packaging'],
    'product range showcase carousel', 0,
    [{'language':'arabic','content_summary':'AlBaik product range carousel — explore menu options'}],
    ['727 likes — swipe format for menu diversity positioning in Saudi F&B'],
    'arabic','hejazi','casual','inviting', True, ['#البيك'],
    'اكتشف قائمة البيك الكاملة واختر وجبتك',
    [], [], 'clean', 'general_saudi', 'none',
    ['product_hero','seasonal_collection_drop','overhead_tabletop_spread'],
    [], 'professional', 'strong', 'medium', 'albaik'),

obs(NORM_A, ULID_A, 'f_and_b', 'DBzJJxmo9Mo', 'image', '2024-08-01',
    'CSR corporate announcement clean', 'white minimal', ['white','green','blue'],
    ['Kaizen workshop banner','AlBaik logo','operations graphic'],
    'corporate CSR workshop invitation', 0,
    [{'language':'arabic','content_summary':'AlBaik invites to Kaizen lean operations workshop'}],
    ['361 likes on operational post — transparency about operations builds trust; Kaizen/zero-waste angle'],
    'arabic','hejazi','formal','professional', True, ['#البيك','#اقوات','#كايزن'],
    'يتشرف البيك واقوات دعوتكم لحضور ورشة برنامج كايزن مبادئ ضبط الهدر',
    [], [], 'clean', 'general_saudi', 'none',
    ['behind_the_craft','educational_explainer','national_day_modernity_heritage'],
    [], 'professional', 'strong', 'low', 'albaik'),

obs(NORM_A, ULID_A, 'f_and_b', 'DGYR6aZt4rJ', 'video', '2025-02-22',
    'founding day heritage motion', 'green gold amber', ['saudi_green','gold','desert_tan'],
    ['1727 founding date typography','heritage calligraphy','AlBaik logo'],
    'Saudi Founding Day branded motion', 0,
    [{'language':'arabic','content_summary':'Saudi Founding Day 1727 — our nation grows in glory'}],
    ['350 likes — founding_day_heritage pattern; 1727 date is the anchor visual for this occasion'],
    'arabic','hejazi','formal','patriotic', False, ['#يوم_بدينا_1727','#البيك'],
    'من يوم بدينا 1727 ووطننا الغالي يزداد شموخًا وعزةً في قلوبنا',
    [], [], 'clean', 'general_saudi', 'founding_day',
    ['founding_day_heritage','founding_day_dirayyah_heritage','national_day_pride'],
    [], 'professional', 'strong', 'medium', 'albaik'),

obs(NORM_A, ULID_A, 'f_and_b', 'DGQ0TdSNjTA', 'video', '2025-02-15',
    'CSR environmental campaign', 'ocean blue natural', ['blue','white','green'],
    ['sea/ocean imagery','volunteer clean-up graphic','AlBaik CSR badge'],
    'environmental CSR campaign post', 0,
    [{'language':'arabic','content_summary':'عينك على البحر volunteer campaign — still open to join'}],
    ['348 likes on environmental CSR — AlBaik positioning as responsible Saudi brand; sea conservation'],
    'arabic','hejazi','formal','responsible', True, ['#البيك','#عينك_على_البحر'],
    'مازالت الفرصة متاحة للمشاركة في الحملة التطوعية عينك على البحر',
    [], [], 'clean', 'general_saudi', 'none',
    ['behind_the_craft','educational_explainer','national_day_modernity_heritage'],
    [], 'professional', 'strong', 'medium', 'albaik'),
]

# ── @shawarmersa ───────────────────────────────────────────────────────────────
NORM_S = 'OGZ-F-AND-B-Reference-009'
ULID_S = '01KS5PZ5T5YSN7GNCCVJ7AZ85T'

ALL_OBS += [
obs(NORM_S, ULID_S, 'f_and_b', 'DCHbSyONS-o', 'image', '2024-10-19',
    'spot the difference puzzle image', 'clean bright grid', ['white','red','cream'],
    ['Shaweeqz shawarma two versions','difference circle highlight'],
    'branded puzzle engagement post', 0,
    [{'language':'arabic','content_summary':'Shaweeqz — find the difference, hard but not for Shawarmer fans'}],
    ['572 likes — #شاويقز puzzle mechanic; "hard but not for a true fan" — loyalty identity hook'],
    'arabic','najdi','casual','playful', False, ['#شاويقز_طعم_مايترجم'],
    'صعبببببة صعببة بس مب على الشاورمري المختلفة وين مكانها؟',
    [], [], 'clean', 'general_saudi', 'none',
    ['gamified_content','customer_voice_ugc','specific_dish_naming'],
    [], 'professional', 'strong', 'high', 'shawarmersa'),

obs(NORM_S, ULID_S, 'f_and_b', 'DCB3Uj7Namb', 'image', '2024-10-14',
    'minimal text expression post', 'clean white', ['white','black','red_brand'],
    ['minimal Arabic typography','shawarmer logo'],
    'minimalist expression viral post', 0,
    [{'language':'arabic','content_summary':'Untranslatable Shaweeqz taste — language itself fails to express it'}],
    ['534 likes — ultra-minimal copy: no food photo, just expression. Voice-first content pattern'],
    'arabic','najdi','casual','witty', False, ['#شاورمر'],
    'تخيّل مب بس التعبير يخون حتى اللغة تخون',
    [], [], 'clean', 'general_saudi', 'none',
    ['classical_arabic_warmth','specific_emotional_state','refusal_framing_positioning'],
    [], 'semi_professional', 'strong', 'high', 'shawarmersa'),

obs(NORM_S, ULID_S, 'f_and_b', 'DCe23sPOuJO', 'image', '2024-10-21',
    'cultural trivia quiz post', 'clean graphic', ['white','red','teal'],
    ['iconic book cover graphic','trivia question text','brand logo'],
    'back to school cultural trivia', 0,
    [{'language':'arabic','content_summary':'Back to school — who recognises this famous cover? answer us'}],
    ['529 likes — back-to-school occasion peg with nostalgic iconic Saudi book cover recognition quiz'],
    'arabic','najdi','casual','nostalgic', False, ['#شاورمر'],
    'بمناسبة العودة عطووني الجواب ما أتوقع مافيه أحد مايعرف هالغلاف الشهير',
    [], [], 'clean', 'general_saudi', 'none',
    ['gamified_content','nostalgia_play','seasonal_collection_drop'],
    [], 'semi_professional', 'strong', 'high', 'shawarmersa'),

obs(NORM_S, ULID_S, 'f_and_b', 'DCCMO42N6T8', 'image', '2024-10-15',
    'minimal text expression post', 'clean white minimal', ['white','black','red'],
    ['bold Arabic typography only','shawarmer wordmark'],
    'language-fails minimalist post', 0,
    [{'language':'arabic','content_summary':'Even language fails to describe the taste — untranslatable'}],
    ['468 likes — series of untranslatable-taste posts; builds anticipation without showing food'],
    'arabic','najdi','casual','witty', False, ['#شاورمر'],
    'تخيّل مب بس التعبير يخون حتى اللغة',
    [], [], 'clean', 'general_saudi', 'none',
    ['classical_arabic_warmth','refusal_framing_positioning','specific_emotional_state'],
    [], 'semi_professional', 'strong', 'high', 'shawarmersa'),

obs(NORM_S, ULID_S, 'f_and_b', 'DCM1YBdO6kU', 'image', '2024-10-16',
    'weekly giveaway question card', 'clean branded graphic', ['red','white','cream'],
    ['#الأحد_الشاورمري branded card','question text','dinner prize icon'],
    'weekly engagement series branded card', 0,
    [{'language':'arabic','content_summary':'#الأحد_الشاورمري — easy question, right answer wins dinner'}],
    ['282 likes — #الأحد_الشاورمري (Shawarmer Sunday) weekly appointment series; dinner giveaway'],
    'arabic','najdi','casual','playful', True, ['#الأحد_الشاورمري'],
    'سؤاااالنا ولا أسهل منه والي يجيب الإجابة يبشر بالعشاء',
    [], [], 'clean', 'general_saudi', 'none',
    ['gamified_content','invitation_to_witness','weekly_series_anchor'],
    [], 'professional', 'strong', 'medium', 'shawarmersa'),

obs(NORM_S, ULID_S, 'f_and_b', 'DCPSQvftxLY', 'image', '2024-10-18',
    'product quote response post', 'clean graphic red', ['red','white','cream'],
    ['Shaweeqz shawarma image','quote speech bubble','brand logo'],
    'product taste testimonial format', 0,
    [{'language':'arabic','content_summary':'Whoever ate Shaweeqz writes their translation — taste beyond words'}],
    ['242 likes — UGC participation mechanic asking fans to translate the untranslatable taste experience'],
    'arabic','najdi','casual','playful', True, ['#شاويقز_طعم_مايترجم'],
    'اللي اكلها يكتب لنا بالصورة ترجمته ويبشر بال',
    [], [], 'clean', 'general_saudi', 'none',
    ['customer_voice_ugc','gamified_content','specific_dish_naming'],
    [], 'professional', 'strong', 'medium', 'shawarmersa'),

obs(NORM_S, ULID_S, 'f_and_b', 'DCCZ4lkutrP', 'image', '2024-10-15',
    'minimalist humor post', 'white clean', ['white','red_brand','black'],
    ['single line Arabic text','minimal shawarmer wordmark'],
    'humor copy-only post', 0,
    [{'language':'arabic','content_summary':'I wanted to bring knowledge, but — (implied: brought shawarma instead)'}],
    ['238 likes — subverted expectations humor; Saudi dry wit style; no food photo needed'],
    'arabic','najdi','casual','humorous', False, ['#شاورمر'],
    'كان ودي أجيب العلم لكن',
    [], [], 'clean', 'general_saudi', 'none',
    ['refusal_framing_positioning','classical_arabic_warmth','contrarian_pivot_line'],
    [], 'semi_professional', 'strong', 'medium', 'shawarmersa'),

obs(NORM_S, ULID_S, 'f_and_b', 'DCEcQHcNk9Z', 'image', '2024-10-17',
    'new product reveal product hero', 'dark dramatic', ['red','black','cream'],
    ['Shaweeqz shawarma hero shot','new badge','product name typography'],
    'new flavor launch product hero', 0,
    [{'language':'arabic','content_summary':'New Shaweeqz shawarma flavor — taste you cannot explain, try it'}],
    ['226 likes — Shaweeqz (شاويقز) product launch; Saudi slang product name; "guaranteed delicious" CTA'],
    'arabic','najdi','casual','excited', True, ['#شاورمر'],
    'استلموا الجديييد يالشاورمرية شاورما جديييدة بنكهة ماتقدر تشرحها',
    [], [], 'clean', 'general_saudi', 'none',
    ['seasonal_collection_drop','product_hero','specific_dish_naming'],
    [], 'professional', 'strong', 'medium', 'shawarmersa'),

obs(NORM_S, ULID_S, 'f_and_b', 'DCe1DOWuzU1', 'video', '2024-10-21',
    'weekly series welcome motion', 'branded warm', ['red','white','orange'],
    ['#الأحد_الشاورمري animated card','welcome back text','brand identity'],
    'weekly series recurring motion', 0,
    [{'language':'arabic','content_summary':'#الأحد_الشاورمري welcome back fans — Sunday is shawarma day'}],
    ['64 likes — appointment content ritual; low-production recurring format anchors weekly habit'],
    'arabic','najdi','casual','warm', False, ['#الأحد_الشاورمري'],
    'هلا ومسهلا ومليييون هلا المشتاق للأحد الشاورمري يرفع يده ويعطيني لايك',
    [], [], 'clean', 'general_saudi', 'none',
    ['invitation_to_witness','warm_najdi_invitational','gamified_content'],
    [], 'semi_professional', 'strong', 'low', 'shawarmersa'),

obs(NORM_S, ULID_S, 'f_and_b', 'DCMzu-NOgGh', 'video', '2024-10-16',
    'quiz question branded motion', 'branded red clean', ['red','white','cream'],
    ['branded question card motion','#الأحد_الشاورمري graphic'],
    'weekly quiz motion', 0,
    [{'language':'arabic','content_summary':'#الأحد_الشاورمري — this week question is untranslatable, see you Sunday evening'}],
    ['65 likes — low engagement but sustains weekly ritual; question-of-week format'],
    'arabic','najdi','casual','playful', False, ['#الأحد_الشاورمري'],
    'مساااء الإجاااازة مستعدين للأحد الشاورمري سؤال اليوم مايترجم',
    [], [], 'clean', 'general_saudi', 'none',
    ['gamified_content','invitation_to_witness'],
    [], 'semi_professional', 'strong', 'low', 'shawarmersa'),
]

# ── @asteribeautysa ────────────────────────────────────────────────────────────
NORM_B = 'OGZ-BEAUTY-Reference-001'
ULID_B = '01KS5PZ5T5J535JPWGJER6R2D1'

ALL_OBS += [
obs(NORM_B, ULID_B, 'beauty', 'DAvCaZrtXiU', 'image', '2024-08-28',
    'product hero editorial beauty', 'soft pink warm studio', ['dusty_pink','gold','white'],
    ['Flextra mascara wand close-up','hybrid brush detail','volume and curl graphic'],
    'beauty product hero editorial', 0,
    [{'language':'arabic','content_summary':'Flextra Volume & Curl Mascara — hybrid brush dual tech, voluminous lashes'}],
    ['3652 likes — highest engagement in entire Asteri set; mascara launch hero post dominates'],
    'arabic','hejazi','casual','aspirational', True, ['#أستيري','#أخوات_تحت_النجوم'],
    'فلكسترا فوليوم اند كورف ماسكارا فرشاة هجينة بتقنية مزدوجة تغطي كل رمش',
    [], [], 'clean', 'general_saudi', 'none',
    ['product_hero','close_up_macro_texture','seasonal_collection_drop'],
    [], 'professional', 'strong', 'high', 'asteribeautysa'),

obs(NORM_B, ULID_B, 'beauty', 'DA8V1_soLN3', 'video', '2024-09-01',
    'back to campus lifestyle reel', 'bright campus natural', ['cream','teal','gold'],
    ['university campus setting','Asteri products in backpack','sisters lifestyle'],
    'back to uni lifestyle campaign', 2,
    [{'language':'arabic','content_summary':'Back to Uni — Asteri edition; sisters under the stars campaign'}],
    ['3420 likes — "أخوات تحت النجوم" (Sisters Under the Stars) — Saudi sisterhood community campaign'],
    'arabic','hejazi','casual','warm', True, ['#أستيري','#أخوات_تحت_النجوم','#مكياج'],
    'العودة إلى الجامعة نسخة أستيري',
    [], [], 'clean', 'general_saudi', 'none',
    ['lifestyle_embed','warm_golden_hour_hero','customer_voice_ugc'],
    [], 'professional', 'strong', 'high', 'asteribeautysa'),

obs(NORM_B, ULID_B, 'beauty', 'DA5xD9PI0Jf', 'video', '2024-08-30',
    'influencer ASMR product review', 'warm pink soft', ['pink','gold','white'],
    ['mascara brush wand detail','lash close-up','influencer hands applying'],
    'ASMR beauty influencer collab', 1,
    [{'language':'arabic','content_summary':'Flextra mascara with influencer — enjoy the ASMR moment lash volume'}],
    ['1127 likes — ASMR beauty content resonates in Saudi beauty space; sensory format'],
    'arabic','hejazi','casual','sensory', False, ['#أستيري','#أخوات_تحت_النجوم'],
    'استمتعي ببعض الإيسمار مع ماسكارا فلكسترا فوليوم اند كورف ماسكارا الجديدة',
    [], [], 'clean', 'general_saudi', 'none',
    ['customer_voice_ugc','close_up_macro_texture','product_hero'],
    [], 'professional', 'strong', 'high', 'asteribeautysa'),

obs(NORM_B, ULID_B, 'beauty', 'DAqlQWoozkb', 'video', '2024-08-26',
    'product reveal beauty sizzle', 'soft studio pink', ['pink','gold','white'],
    ['mascara product spinning reveal','lash before-after graphic','brand logo'],
    'mascara product reveal video', 0,
    [{'language':'arabic','content_summary':'Flextra Volume & Curl — panoramic lash effect product reveal video'}],
    ['462 likes — product reveal before launch builds anticipation in Saudi beauty community'],
    'arabic','hejazi','casual','anticipatory', True, ['#أستيري'],
    'فلكسترا فوليوم اند كورف ماسكارا رموش كثيفة ومجعدة ومرفوعة',
    [], [], 'clean', 'general_saudi', 'none',
    ['seasonal_collection_drop','product_hero','close_up_macro_texture'],
    [], 'professional', 'strong', 'high', 'asteribeautysa'),

obs(NORM_B, ULID_B, 'beauty', 'DA0nezFo26R', 'video', '2024-09-02',
    'beauty tutorial how-to', 'warm pink studio', ['pink','black','gold'],
    ['mascara application step-by-step','lash transformation close-up'],
    'beauty application tutorial', 1,
    [{'language':'arabic','content_summary':'Simple tutorial: how to apply Flextra Mascara — steps + results'}],
    ['53 likes — tutorial format; educational in beauty sector; "how-to" builds purchase confidence'],
    'arabic','hejazi','casual','educational', False, ['#أستيري','#أخوات_تحت_النجوم'],
    'إليك توتوريال بسيط حول كيفية تطبيق فلكسترا فوليوم اند كورف ماسكارا الجديدة',
    [], [], 'clean', 'general_saudi', 'none',
    ['educational_explainer','behind_the_craft','product_hero'],
    [], 'professional', 'strong', 'low', 'asteribeautysa'),

obs(NORM_B, ULID_B, 'beauty', 'DA3MUIJogIW', 'image', '2024-09-04',
    'BTS photo album grid', 'warm candid natural', ['cream','pink','teal'],
    ['behind-scenes shooting day photos','team with products','candid laughter'],
    'behind the scenes photo album', 3,
    [{'language':'arabic','content_summary':'Our recent photo album — Sisters Under the Stars BTS moments'}],
    ['31 likes — BTS album humanises brand; team visibility builds trust for Saudi clean beauty brand'],
    'arabic','hejazi','casual','authentic', False, ['#أستيري','#أخوات_تحت_النجوم'],
    'ألبوم صورنا مؤخرًا',
    [], [], 'clean', 'general_saudi', 'none',
    ['behind_the_craft','customer_voice_ugc','warm_golden_hour_hero'],
    [], 'semi_professional', 'moderate', 'low', 'asteribeautysa'),

obs(NORM_B, ULID_B, 'beauty', 'DAyS25dNve6', 'image', '2024-08-27',
    'product specification hero card', 'clean soft pink', ['dusty_pink','black','white'],
    ['mascara product flat lay','formula ingredient list','panoramic effect graphic'],
    'beauty product specification card', 0,
    [{'language':'arabic','content_summary':'Flextra mascara — instantly thickened curled, panoramic eye effect, formula details'}],
    ['49 likes — ingredient/formula transparency card; builds ingredient trust in Saudi beauty space'],
    'arabic','hejazi','casual','informative', True, ['#أستيري'],
    'تمنح الماسكارا المكثفة والمجعدة على الفور الرموش تأثيرا بانوراميا',
    [], [], 'clean', 'general_saudi', 'none',
    ['educational_explainer','product_hero','behind_the_craft'],
    [], 'professional', 'strong', 'low', 'asteribeautysa'),

obs(NORM_B, ULID_B, 'beauty', 'DAs_8vfN5xE', 'image', '2024-08-29',
    'aspirational lash product hero', 'dark editorial', ['black','gold','pink'],
    ['dramatic lash close-up','brand name typography','new heights copy'],
    'aspirational editorial product image', 0,
    [{'language':'arabic','content_summary':'Lashes that reach new heights — lift curl volume, get Flextra now'}],
    ['54 likes — "new heights" aspiration + lift/curl/volume triple benefit = Saudi beauty purchase drivers'],
    'arabic','hejazi','casual','aspirational', True, ['#أستيري'],
    'رموش تصل إلى ارتفاعات جديدة ترفع وتجعّد وتزيد من حجمها',
    [], [], 'clean', 'general_saudi', 'none',
    ['product_hero','specific_emotional_state','invitation_to_witness'],
    [], 'professional', 'strong', 'low', 'asteribeautysa'),

obs(NORM_B, ULID_B, 'beauty', 'DAn2W9lNMSc', 'image', '2024-08-25',
    'product teaser launch day card', 'pink gold soft', ['pink','gold','cream'],
    ['tomorrow teaser graphic','Asteri logo','launch countdown'],
    'product launch day teaser', 0,
    [{'language':'arabic','content_summary':'Tomorrow is the big day — Flextra mascara launch countdown teaser'}],
    ['32 likes on teaser — day-before launch post; builds community anticipation for mascara drop'],
    'arabic','hejazi','casual','excited', False, ['#أستيري'],
    'غدًا هو اليوم الكبير',
    [], [], 'clean', 'general_saudi', 'none',
    ['seasonal_collection_drop','specific_emotional_state'],
    [], 'professional', 'strong', 'low', 'asteribeautysa'),

obs(NORM_B, ULID_B, 'beauty', 'DAvCaZrtXiU', 'image', '2024-08-28',
    'product hero feature list editorial', 'soft pink studio', ['pink','gold','white'],
    ['mascara product on pink surface','brush technology graphic','volume chart'],
    'mascara feature breakdown hero', 0,
    [{'language':'arabic','content_summary':'Flextra mascara features — volume curl lift panoramic in one product'}],
    ['Mascara hero post variant — feature breakdown format used in Saudi beauty product launches'],
    'arabic','hejazi','casual','educational', True, ['#أستيري'],
    'فلكسترا: ماسكارا لما تريدين دفعة إضافية من الرفع والحجم',
    [], [], 'clean', 'general_saudi', 'none',
    ['product_hero','educational_explainer','close_up_macro_texture'],
    [], 'professional', 'strong', 'medium', 'asteribeautysa'),
]

# ── @alromansiahksa ────────────────────────────────────────────────────────────
NORM_R = 'OGZ-F-AND-B-Reference-011'
ULID_R = '01KS5R0A1701GF09TMG4E65H5C'

ALL_OBS += [
obs(NORM_R, ULID_R, 'f_and_b', 'DYhVXYdDmMs', 'carousel_slide', '2026-05-19',
    'swipe menu carousel', 'warm branded', ['orange','cream','brown'],
    ['multiple dishes carousel','swipe prompt overlay','brand logo'],
    'menu exploration swipe carousel', 0,
    [{'language':'arabic','content_summary':'Don\'t resist hunger — swipe and order what you crave from app'}],
    ['"لا تقاوم الجوع" — hunger resistance copy; swipe carousel drives app ordering behaviour'],
    'arabic','najdi','casual','playful', True, ['#مطاعم_الرومانسية'],
    'لا تقاوم الجوع اسحب الشاشة واطلب اللي تشتهيه من التطبيق',
    [], [], 'clean', 'general_saudi', 'none',
    ['product_hero','gamified_content','invitation_to_witness'],
    [], 'professional', 'strong', 'low', 'alromansiahksa'),

obs(NORM_R, ULID_R, 'f_and_b', 'DYerHNrlax-', 'image', '2026-05-14',
    'signature dish detail macro', 'warm amber studio', ['golden_brown','orange','cream'],
    ['signature marinated dish close-up','branded plate','sauce glistening'],
    'signature dish macro hero', 0,
    [{'language':'arabic','content_summary':'Some dishes you repeat endlessly because the marinade is the reason'}],
    ['"تتبيلتها بالمقام الأول" — marinade/spice mastery as Saudi F&B differentiator; repeat-order loyalty driver'],
    'arabic','najdi','casual','warm', False, ['#مطاعم_الرومانسية'],
    'بعض الأصناف تكررها بدون ملل عشان تتبيلتها بالمقام الأول',
    [], [], 'clean', 'general_saudi', 'none',
    ['product_hero','close_up_macro_texture','specific_dish_naming'],
    [], 'professional', 'strong', 'low', 'alromansiahksa'),

obs(NORM_R, ULID_R, 'f_and_b', 'DYbyzHgFS_Y', 'image', '2026-05-15',
    'traditional dish local proximity', 'warm natural', ['golden_saffron','brown','cream'],
    ['haneedh rice dish','traditional clay pot','nearby location graphic'],
    'traditional Saudi dish local availability', 0,
    [{'language':'arabic','content_summary':'No need to travel far for haneedh — we\'re in your neighbourhood'}],
    ['حنيذ (haneedh - slow-cooked lamb/rice) as local accessibility hook; Saudi heritage dish proximity claim'],
    'arabic','najdi','casual','warm', False, ['#مطاعم_الرومانسية'],
    'ما يحتاج تسافر من ديرة لديرة بس عشان تذوق الحنيذ',
    [], [], 'clean', 'riyadh', 'none',
    ['product_hero','warm_najdi_invitational','specific_dish_naming'],
    [], 'professional', 'strong', 'low', 'alromansiahksa'),

obs(NORM_R, ULID_R, 'f_and_b', 'DYUClVACEyq', 'video', '2026-05-16',
    'spicy product challenge video', 'dramatic warm dark', ['deep_red','orange','black'],
    ['haraq spicy box','flame graphic','fire emoji overlay'],
    'spicy product sizzle video', 0,
    [{'language':'arabic','content_summary':'If your mood is fiery today don\'t go past الحراق box — taste ignites love in heart'}],
    ['"طعم يولّع قلبك حب" — fire/love metaphor for spicy product; Saudi emotional food copy style'],
    'arabic','najdi','casual','bold', True, ['#مطاعم_الرومانسية'],
    'إذا مزاجك اليوم نار لا تتعدّى بوكس الحراق طعم يولّع قلبك حب',
    [], [], 'clean', 'riyadh', 'none',
    ['product_hero','classical_arabic_warmth','specific_dish_naming'],
    [], 'professional', 'strong', 'low', 'alromansiahksa'),

obs(NORM_R, ULID_R, 'f_and_b', 'DYMU0oFjg5f', 'carousel_slide', '2026-05-16',
    'choose your path decision carousel', 'bright branded', ['orange','cream','teal'],
    ['branching path graphic','dish option A vs B','swipe prompt'],
    'decision journey swipe carousel', 0,
    [{'language':'arabic','content_summary':'Choose your path to the dish you\'re craving — swipe to decide'}],
    ['Interactive choose-your-path carousel maps meal preference to dish; app ordering funnel'],
    'arabic','najdi','casual','playful', True, ['#مطاعم_الرومانسية'],
    'اختر طريقك للصنف اللي خاطرك فيه',
    [], [], 'clean', 'general_saudi', 'none',
    ['gamified_content','product_hero','invitation_to_witness'],
    [], 'professional', 'strong', 'low', 'alromansiahksa'),

obs(NORM_R, ULID_R, 'f_and_b', 'DYHfBx0EnK5', 'image', '2026-05-16',
    'multi-cuisine product hero', 'warm studio', ['golden','white','herb_green'],
    ['lasagna plated portion','Italian herbs garnish','branded plate'],
    'international dish product hero', 0,
    [{'language':'arabic','content_summary':'Make your lunch Italian today — Al-Romansiah lasagna perfected, on your doorstep'}],
    ['"خل غداك اليوم إيطالي" — multi-cuisine positioning within Saudi restaurant brand; delivery convenience'],
    'arabic','najdi','casual','inviting', True, ['#مطاعم_الرومانسية'],
    'خل غداك اليوم إيطالي لازانيا مطاعم الرومانسية لذة على أصولها وعلى جوك',
    [], [], 'clean', 'riyadh', 'none',
    ['product_hero','specific_dish_naming','invitation_to_witness'],
    [], 'professional', 'strong', 'low', 'alromansiahksa'),

obs(NORM_R, ULID_R, 'f_and_b', 'DYE2-R0DC6c', 'image', '2026-05-15',
    'traditional dish close-up poetic', 'warm amber', ['golden_saffron','white','brown'],
    ['maqluba chicken dish flipped','traditional plating','steam rising'],
    'traditional Saudi dish macro', 0,
    [{'language':'arabic','content_summary':'Chicken maqluba — its delight flips your mind and steals your heart'}],
    ['"مقلوبة" (upside-down rice) — name pun: "تشقلب عقلك" (flips your mind); classic Saudi wordplay in food copy'],
    'arabic','najdi','casual','poetic', False, ['#مطاعم_الرومانسية'],
    'مقلوبة الدجاج لذتها تشقلب عقلك وتخطف قلبك',
    [], [], 'clean', 'riyadh', 'none',
    ['product_hero','classical_arabic_warmth','specific_dish_naming'],
    [], 'professional', 'strong', 'low', 'alromansiahksa'),

obs(NORM_R, ULID_R, 'f_and_b', 'DYCCTOFGheK', 'image', '2026-05-15',
    'brand positioning statement hero', 'warm minimal clean', ['orange','cream','white'],
    ['brand tagline typography','subtle food background','orange brand color'],
    'brand value statement post', 0,
    [{'language':'arabic','content_summary':'Al-Romansiah understands you without explanation — adjusts to suit you, even without heat'}],
    ['"تفهمك بدون تفصيل" (understands you without detail) — empathy brand positioning; "بدون نار" (without fire/spice) for those who prefer mild'],
    'arabic','najdi','casual','warm', False, ['#مطاعم_الرومانسية'],
    'مطاعم الرومانسية تفهمك بدون تفصيل وتضبطها لك حتى بدون نار',
    [], [], 'clean', 'general_saudi', 'none',
    ['classical_arabic_warmth','warm_najdi_invitational','refusal_framing_positioning'],
    [], 'professional', 'strong', 'low', 'alromansiahksa'),

obs(NORM_R, ULID_R, 'f_and_b', 'DYedLFSiGrW', 'video', '2026-05-14',
    'lunch engagement question video', 'warm bright', ['orange','golden','cream'],
    ['lunch spread montage','question overlay text'],
    'lunch daypart engagement video', 0,
    [{'language':'arabic','content_summary':'What do you feel like having for lunch today? — Al-Romansiah serves it'}],
    ['"وش مشتهي تتغدى اليوم؟" — daily lunch prompt; 80 likes suggests solid recurring engagement driver'],
    'arabic','najdi','casual','conversational', False, ['#مطاعم_الرومانسية'],
    'وش مشتهي تتغدى اليوم؟',
    [], [], 'clean', 'riyadh', 'none',
    ['invitation_to_witness','product_hero','warm_najdi_invitational'],
    [], 'professional', 'strong', 'medium', 'alromansiahksa'),

obs(NORM_R, ULID_R, 'f_and_b', 'DYW8lLAlWBi', 'video', '2026-05-16',
    'golden product sizzle reel', 'warm golden studio', ['deep_golden','crispy_brown','orange'],
    ['golden fried chicken rotating 360','branded box','dipping sauce'],
    'golden product 360 hero video', 0,
    [{'language':'arabic','content_summary':'The Golden — you can\'t resist its look or its taste'}],
    ['"الذهبية اللي ما تقدر تقاوم شكلها ولا طعمها" — irresistibility double-hook (visual + taste); gold colour aesthetic'],
    'arabic','najdi','casual','enticing', True, ['#مطاعم_الرومانسية'],
    'الذهبية اللي ما تقدر تقاوم شكلها ولا طعمها',
    [], [], 'clean', 'riyadh', 'none',
    ['product_hero','close_up_macro_texture','specific_dish_naming'],
    [], 'professional', 'strong', 'medium', 'alromansiahksa'),
]

# Write all observations
sectors = {'f_and_b': REPO/'11_who_to_learn_from'/'observations'/'f_and_b',
           'beauty':  REPO/'11_who_to_learn_from'/'observations'/'beauty'}
for d in sectors.values():
    d.mkdir(parents=True, exist_ok=True)

written = 0
for o in ALL_OBS:
    sector = o['sector']
    path = sectors[sector] / f"{o['observation_ulid']}.json"
    path.write_text(json.dumps(o, ensure_ascii=False, indent=2))
    written += 1

# Summary
from collections import Counter
by_account = Counter(o['account_handle_normalized'] for o in ALL_OBS)
norm_to_handle = {
    'OGZ-F-AND-B-Reference-006': '@herfyfsc',
    'OGZ-F-AND-B-Reference-007': '@kuduksa',
    'OGZ-F-AND-B-Reference-008': '@albaik',
    'OGZ-F-AND-B-Reference-009': '@shawarmersa',
    'OGZ-F-AND-B-Reference-011': '@alromansiahksa',
    'OGZ-BEAUTY-Reference-001':  '@asteribeautysa',
}
print(f'Written: {written} new observations')
for norm, cnt in by_account.items():
    print(f'  {norm_to_handle.get(norm, norm)}: +{cnt}')
print('Done.')
