#!/usr/bin/env python3
"""Write 12 observations for @pizzahutsaudi (Tier 4 anti-pattern account)."""
import json, pathlib

REPO = pathlib.Path('/Users/abarihm/Desktop/ogz-knowledge')
OUT  = REPO / '11_who_to_learn_from' / 'observations' / 'f_and_b'
OUT.mkdir(parents=True, exist_ok=True)

ACCOUNT_NORM = "OGZ-F-AND-B-Reference-038"
ACCOUNT_ULID = "01KS5XZ0Y071HFE865V215DE1C"
SECTOR       = "f_and_b"

def obs(ulid, shortcode, content_type, capture_date,
        composition_style, lighting, colors, props, setting, chars_count, chars_gender, chars_dress, overlays, notable,
        language, dialect, register, tone, notable_phrases, cta,
        hard_blocks, soft_flags, compliance,
        region, occasion, hosp_cues, heritage, free_notes,
        patterns,
        prod_quality, brand_consistency, engagement_potential):
    return {
        "observation_ulid": ulid,
        "schema_version": 1,
        "account_handle_normalized": ACCOUNT_NORM,
        "account_ulid": ACCOUNT_ULID,
        "sector": SECTOR,
        "content_ref": {
            "filename": f"{shortcode}.jpg",
            "platform": "instagram",
            "content_type": content_type,
            "capture_date": capture_date,
            "source_url": f"https://www.instagram.com/p/{shortcode}/"
        },
        "visual_observations": {
            "composition_style": composition_style,
            "lighting": lighting,
            "color_palette_dominant": colors,
            "props_visible": props,
            "setting": setting,
            "characters_visible": {"count": chars_count, "gender": chars_gender, "dress_code": chars_dress},
            "text_overlays": overlays,
            "notable_visual_elements": notable
        },
        "voice_observations": {
            "language": language,
            "dialect_detected": dialect,
            "register": register,
            "tone": tone,
            "notable_phrases": notable_phrases,
            "call_to_action_present": cta
        },
        "compliance_check": {
            "hard_blocks_triggered": hard_blocks,
            "soft_flags": soft_flags,
            "overall_compliance": compliance
        },
        "cultural_notes": {
            "regional_orientation_detected": region,
            "occasion_relevance": occasion,
            "hospitality_cues": hosp_cues,
            "heritage_vs_modern": heritage,
            "free_notes": free_notes
        },
        "pattern_matches": patterns,
        "quality_assessment": {
            "production_quality": prod_quality,
            "brand_consistency_with_account": brand_consistency,
            "engagement_potential": engagement_potential
        },
        "provenance": {
            "source": f"benchmark:@pizzahutsaudi; content:{shortcode}.jpg",
            "date_added": "2026-05-21T18:50:00Z",
            "confirmer": "claude_code_extraction",
            "confidence": "inferred",
            "scope": "sector:f_and_b tier:4"
        }
    }

records = [
    obs("01KS5XZ1X8PPG2X7R5JQC42EJ5",
        "DXw-I85gBIN", "image", "2026-05-28",
        "vertical product hero — hand holding pizza slice against solid red background",
        "studio artificial", ["red","white","dark_brown"],
        ["pizza_slice","hand"], "studio solid red background",
        1, "unknown", "casual",
        [{"language":"arabic","content_summary":"مو أي جديد جديد / عجينة من قلب إيطاليا — new Italian crust announcement"}],
        ["hand-held pizza slice occupies 60% of frame","solid brand red dominates","Italian origin as aspirational claim"],
        "arabic", "saudi_colloquial", "casual", "excitement",
        ["مو أي جديد"], True,
        [], ["foreign_cuisine_Italian_framed_as_aspirational"], "soft_flagged",
        "general_saudi", None, [], "western_import",
        "Tier 4 anti-pattern: Italian crust positioned as superior due to foreign origin. No Saudi cultural warmth, no hospitality cues, pure product activation on global brand template.",
        [{"pattern_slug":"product_hero","confidence":"strong","notes":"hand-held slice hero on solid red — global template"}],
        "professional", "strong", "medium"),

    obs("01KS5XZ20CE6RHXQAQPDH4AFAX",
        "DXw-FfhANoE", "image", "2026-05-28",
        "centered brand logo on neutral checkerboard background",
        "flat neutral", ["grey","red","white"],
        ["pizza_hut_arabic_logo"], "transparent checkerboard background",
        0, "none", "none",
        [{"language":"arabic","content_summary":"بيتزا هت Arabic calligraphy logo"}],
        ["logo-only static post","no product, no people, no context"],
        "arabic", "none", "formal", "neutral",
        [], False,
        [], [], "clean",
        "general_saudi", None, [], "western_import",
        "Tier 4: Brand identity static post. No content, no message. Lowest engagement value.",
        [],
        "professional", "strong", "low"),

    obs("01KS5XZ23GRHEM3E2MSH4DMDZS",
        "DXw-ApwAFhu", "image", "2026-05-28",
        "overhead product shot with red header bar text overlay",
        "studio artificial", ["red","orange","cream","white"],
        ["whole_pizza_overhead","brand_header_bar","brand_footer_tagline"],
        "studio solid background",
        0, "none", "none",
        [{"language":"arabic","content_summary":"جديدنا العجينة الإيطالية — top header"},
         {"language":"arabic","content_summary":"طيّب أوقاتك™ — brand tagline footer"}],
        ["clean macro overhead pizza","red header/white text layout typical global QSR template","tagline طيّب أوقاتك is generic lifestyle, not Saudi-cultural"],
        "arabic", "saudi_colloquial", "casual", "enthusiasm",
        ["طيّب أوقاتك"], True,
        [], ["Italian_origin_as_premium","generic_lifestyle_tagline_not_Saudi_identity"], "soft_flagged",
        "general_saudi", None, [], "western_import",
        "Tier 4: New product launch uses Italian origin as selling point. Brand tagline (طيّب أوقاتك) is lifestyle-generic, not culturally rooted. Template matches global Pizza Hut playbook.",
        [{"pattern_slug":"seasonal_collection_drop","confidence":"moderate","notes":"new Italian crust product launch"},
         {"pattern_slug":"close_up_macro_texture","confidence":"moderate","notes":"overhead pizza macro with visible texture"}],
        "professional", "strong", "medium"),

    obs("01KS5XZ26MX9G8FGVSQE8Z5379",
        "DYkCRVyALeA", "carousel", "2026-05-26",
        "person-product interaction on solid red background with graphic camera frame overlay",
        "studio artificial", ["red","white","cream"],
        ["pizza_slice","camera_frame_graphic_overlay","pizza_hut_logo"],
        "studio solid red background",
        1, "male", "thobe",
        [{"language":"arabic","content_summary":"آخر قطعة لمين؟ — last slice for who?"},
         {"language":"arabic","content_summary":"brand logo top center"}],
        ["man in white thobe holds pizza slice obscuring face","thobe used as cultural prop, not genuine cultural expression","camera frame graphic = social media activation mechanic"],
        "arabic", "saudi_colloquial", "casual", "playful",
        ["آخر قطعة لمين؟"], True,
        [], ["thobe_as_costume_prop_not_cultural_expression","western_social_activation_mechanic"], "soft_flagged",
        "general_saudi", None, [], "western_import",
        "Tier 4: Thobe used as a visual prop to signal 'Saudi audience' without genuine cultural content. Camera frame overlay is a global social mechanic. Discount CTA hidden in caption.",
        [{"pattern_slug":"invitation_to_witness","confidence":"weak","notes":"engagement-bait social mechanic — who gets the last slice?"}],
        "professional", "strong", "medium"),

    obs("01KS5XZ29RAV4RRXG07HN7JVAX",
        "DYb_O2SAGes", "image", "2026-05-25",
        "extreme overhead macro pizza with discount sticker overlay",
        "studio artificial", ["red","orange","brown"],
        ["whole_pizza_macro_overhead","discount_percentage_sticker","brand_tagline"],
        "studio solid background",
        0, "none", "none",
        [{"language":"arabic","content_summary":"يا مطبول الغبات تعال استلم من الفرع — colloquial tease"},
         {"language":"arabic","content_summary":"خصم 30% — 30% discount sticker overlay"}],
        ["playful colloquial insult تعال as engagement hook","macro texture shot repurposed for discount not sensory appreciation","طيّب أوقاتك brand footer"],
        "arabic", "saudi_colloquial", "casual", "transactional",
        ["يا مطبول الغبات","خصم 30%"], True,
        [], ["discount_dominant_no_cultural_warmth","colloquial_tease_without_hospitality_frame"], "soft_flagged",
        "general_saudi", None, [], "western_import",
        "Tier 4: Macro pizza shot used as discount vehicle. Colloquial tease (يا مطبول الغبات) attempts cultural warmth but is purely transactional. No storytelling, no occasion, no heritage.",
        [{"pattern_slug":"close_up_macro_texture","confidence":"moderate","notes":"overhead macro used for discount, not sensory beauty"}],
        "professional", "strong", "low"),

    obs("01KS5XZ2CW0GB6KC9QA0MZ17QK",
        "DYO5hA8AG5s", "image", "2026-05-23",
        "product catalogue grid — three whole pizzas on solid red background with pricing",
        "studio artificial", ["red","cream","white"],
        ["three_whole_pizzas","brand_logo","price_text_66SAR","app_download_CTA"],
        "studio solid red background",
        0, "none", "none",
        [{"language":"arabic","content_summary":"اشتري 2 بيتزا كبير واحصل على وحدة مجانًا 1+1=3"},
         {"language":"arabic","content_summary":"66 ريال / حصري على التطبيق فقط"}],
        ["three pizzas arranged in triangular layout","large price number dominates","app-exclusive badge creates friction"],
        "arabic", "saudi_colloquial", "casual", "transactional",
        ["1+1=3","مجانًا","حصري على التطبيق"], True,
        [], ["pure_discount_catalogue_zero_cultural_identity","app_gating_creates_friction"], "soft_flagged",
        "general_saudi", None, [], "western_import",
        "Tier 4: Textbook discount catalogue post. Three products + price + CTA = zero cultural value. App exclusivity gates the offer. Identical to global Pizza Hut playbook.",
        [{"pattern_slug":"product_hero","confidence":"moderate","notes":"product catalogue layout for promo comparison — not a hero"}],
        "professional", "strong", "low"),

    obs("01KS5XZ2G0F3F55Z488YAGVDCK",
        "DYNOyPiAFYX", "image", "2026-05-22",
        "split-screen two-column comparison graphic on white background",
        "studio flat", ["white","red","black"],
        ["two_identical_pizza_photos","decorative_arrows","crown_icons","star_icons"],
        "studio white background",
        0, "none", "none",
        [{"language":"arabic","content_summary":"فريق التسويق / جيل الألفية — Millennial marketing team description"},
         {"language":"arabic","content_summary":"فريق السوشيال / جيل زد — Gen Z social team description"}],
        ["identical pizza images left and right","Millennial vs Gen Z meme format","playful internal brand voice but no Saudi identity"],
        "arabic", "saudi_colloquial", "casual", "humorous",
        ["فريق التسويق","فريق السوشيال","جيل الألفية","جيل زد"], False,
        [], ["western_Gen_Z_vs_Millennial_meme_format_applied_to_Saudi","no_Saudi_cultural_identity"], "soft_flagged",
        "general_saudi", None, [], "western_import",
        "Tier 4: Western social media meme (Millennial vs Gen Z) grafted onto Saudi market. Playful but culturally rootless. No Saudi identity signal.",
        [{"pattern_slug":"split_screen_before_after","confidence":"strong","notes":"split-screen format used as meme mechanic, not product comparison"}],
        "professional", "strong", "medium"),

    obs("01KS5XZ2K4SQWW7FE4N1EE043E",
        "DYMqn2aDOoi", "image", "2026-05-21",
        "mosaic grid with dark checkerboard tiles — price-dominant layout",
        "studio artificial", ["black","red","white"],
        ["pizza_macro_tile","pixel_brand_icon","price_text_29SAR","pixel_face_icons"],
        "dark checkerboard mosaic background",
        0, "none", "none",
        [{"language":"arabic","content_summary":"2 بيتزا كبيرة بـ 29 ريال للوحدة"},
         {"language":"arabic","content_summary":"pixel art brand icons and face emoticons"}],
        ["pixel/gaming aesthetic applied to food discount","dark mosaic tiling is unique but culturally irrelevant","price is the dominant visual element"],
        "arabic", "saudi_colloquial", "casual", "transactional",
        ["29 ريال للوحدة"], True,
        [], ["gaming_pixel_aesthetic_irrelevant_to_Saudi_food_culture","price_dominant_no_storytelling"], "soft_flagged",
        "general_saudi", None, [], "western_import",
        "Tier 4: Gaming/pixel aesthetic applied to pizza discount. Visually distinctive but culturally disconnected from Saudi F&B identity. Pure transactional content.",
        [{"pattern_slug":"product_hero","confidence":"weak","notes":"mosaic tile product display serving only promotional function"}],
        "professional", "strong", "low"),

    obs("01KS5XZ2P842N4FHZD8YFYTC66",
        "DYhZiQ5DGus", "image", "2026-05-20",
        "graphic text-only post — speech bubble on dark checkerboard background",
        "flat dark", ["black","red","white"],
        ["speech_bubble_graphic","brand_tagline_footer"],
        "dark checkerboard background",
        0, "none", "none",
        [{"language":"arabic","content_summary":"كيف تصير جاينت بوكس — rhetorical question in speech bubble"},
         {"language":"arabic","content_summary":"حلّي أوقاتك™ — brand tagline footer"}],
        ["no food product visible","pure filler graphic post","speech bubble mechanic from global playbook"],
        "arabic", "saudi_colloquial", "casual", "playful",
        ["كيف تصير جاينت بوكس","حلّي أوقاتك"], True,
        [], [], "clean",
        "general_saudi", None, [], "western_import",
        "Tier 4: No food, no culture, pure filler graphic. Brand tagline. Lowest content value in the corpus.",
        [],
        "professional", "strong", "low"),

    obs("01KS5XZ2SCVPVTX363SN6FCCW8",
        "DYSU4-JztAw", "video", "2026-05-19",
        "product reveal video — pizza dough and cheese pull close-up",
        "studio artificial", ["red","cream","orange","white"],
        ["pizza_dough_texture","cheese_pull","brand_overlay","Italian_flag_emoji"],
        "studio controlled",
        0, "none", "none",
        [{"language":"arabic","content_summary":"بيتزا العجينة الإيطالية 🇮🇹 تاكلها بعينك قبل فمك اطلب الحين"},
         {"language":"arabic","content_summary":"brand logo and campaign name overlay"}],
        ["Italian flag emoji in caption foregrounds foreign origin","cheese pull macro creates sensory appetite appeal","'eat it with your eyes first' = sensory copy without cultural soul"],
        "arabic", "saudi_colloquial", "casual", "excitement",
        ["تاكلها بعينك قبل فمك","العجينة الإيطالية"], True,
        [], ["Italian_flag_as_aspirational_marker","no_Saudi_cultural_launch_framing"], "soft_flagged",
        "general_saudi", None, [], "western_import",
        "Tier 4: Italian flag emoji and 'from Italy' framing positions foreign origin as premium quality. No Saudi cultural context for the launch.",
        [{"pattern_slug":"seasonal_collection_drop","confidence":"strong","notes":"new Italian crust product launch video"},
         {"pattern_slug":"close_up_macro_texture","confidence":"moderate","notes":"cheese pull and dough texture macro"}],
        "professional", "strong", "medium"),

    obs("01KS5XZ2WGVBHXF4W6305FATZY",
        "DYXXx5YTqrd", "video", "2026-05-18",
        "documentary-style CSR video — accessible franchise workplace",
        "natural mixed", ["red","white","neutral"],
        ["restaurant_interior","accessible_workspace_equipment","staff_members"],
        "restaurant interior",
        2, "mixed", "professional_casual",
        [{"language":"arabic","content_summary":"مكان كل واحد يقدر يبدع فيه — accessible creative workplace CTA"},
         {"language":"arabic","content_summary":"فروع مجهزة لتسهيل العمل لذوي الاحتياجات الخاصة"}],
        ["franchise branches equipped for employees with disabilities","real employees visible in work settings","CSR framing without Saudi cultural specificity"],
        "arabic", "saudi_colloquial", "casual", "caring",
        ["مكان كل واحد يقدر يبدع"], False,
        [], ["CSR_content_global_template_not_Saudi_specific"], "clean",
        "general_saudi", None, [], "western_import",
        "Tier 4: Workplace accessibility CSR post. Genuine social value but framed as global QSR CSR template without any Saudi-specific cultural warmth or heritage connection.",
        [{"pattern_slug":"educational_explainer","confidence":"weak","notes":"CSR accessibility showcase"}],
        "professional", "strong", "medium"),

    obs("01KS5XZ2ZMDS3AR0RGXJVZ9CJD",
        "DYhrpFVztUN", "video", "2026-05-20",
        "product reveal video — pizza box opening and dough presentation",
        "studio artificial", ["red","cream","white"],
        ["pizza_box","Italian_crust_reveal","brand_campaign_overlay"],
        "studio controlled",
        0, "none", "none",
        [{"language":"arabic","content_summary":"جديدنا، ما راح تقدرون تقاومونه — campaign hook"},
         {"language":"arabic","content_summary":"بيتزا بالعجينة الإيطالية، راح تغير مفهومك عن البيتزا"}],
        ["pizza box opening reveal mechanic","'will change your concept of pizza' = positioning Italian as superior","no Saudi cultural frame for new product"],
        "arabic", "saudi_colloquial", "casual", "excitement",
        ["ما راح تقدرون تقاومونه","راح تغير مفهومك"], True,
        [], ["Italian_crust_positioned_as_superior_import"], "soft_flagged",
        "general_saudi", None, [], "western_import",
        "Tier 4: Second Italian crust launch video. Positions the product as a paradigm shift based on Italian origin. No Saudi cultural entry point.",
        [{"pattern_slug":"seasonal_collection_drop","confidence":"strong","notes":"Italian crust launch campaign second video"}],
        "professional", "strong", "medium"),
]

written = 0
for r in records:
    p = OUT / f"{r['observation_ulid']}.json"
    p.write_text(json.dumps(r, ensure_ascii=False, indent=2))
    written += 1

print(f"Written: {written} observations for @pizzahutsaudi → {OUT}")
