#!/usr/bin/env python3
"""Write 15 @asteribeautysa (beauty) and 15 @shawarmersa (f_and_b) observations."""
import json, random, time
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CROCKFORD = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
_offset = 0

def make_ulid():
    global _offset
    t = int(time.time() * 1000) + _offset; _offset += 1
    t_part = ""; v = t
    for _ in range(10): t_part = CROCKFORD[v & 0x1F] + t_part; v >>= 5
    r = random.getrandbits(80); r_part = ""
    for _ in range(16): r_part = CROCKFORD[r & 0x1F] + r_part; r >>= 5
    return t_part + r_part

NOW = datetime.now(timezone.utc).isoformat()

def build_obs(post, handle_norm, account_ulid, sector, obs_dir):
    vis = post["visual"]
    return {
        "observation_ulid": make_ulid(),
        "schema_version": 1,
        "account_handle_normalized": handle_norm,
        "account_ulid": account_ulid,
        "sector": sector,
        "content_ref": {
            "filename": f"{post['shortcode']}.jpg",
            "platform": "instagram",
            "content_type": post["content_type"],
            "capture_date": post["capture_date"],
            "source_url": f"https://www.instagram.com/p/{post['shortcode']}/"
        },
        "visual_observations": {
            "composition_style": vis["composition_style"],
            "lighting": vis["lighting"],
            "color_palette_dominant": vis["color_palette_dominant"],
            "props_visible": vis["props_visible"],
            "setting": vis["setting"],
            "characters_visible": vis["characters_visible"],
            "text_overlays": vis["text_overlays"],
            "notable_visual_elements": vis["notable_visual_elements"]
        },
        "voice_observations": post["voice"],
        "compliance_check": {"hard_blocks_triggered": [], "soft_flags": [], "overall_compliance": "clean"},
        "cultural_notes": post["cultural_notes"],
        "pattern_matches": post["patterns"],
        "quality_assessment": {
            "production_quality": "professional",
            "brand_consistency_with_account": "strong",
            "engagement_potential": "high" if post["likes"] >= 500 else "medium" if post["likes"] >= 60 else "low"
        },
        "provenance": {
            "source": f"benchmark:@{handle_norm}; content:{post['shortcode']}; browser_collected:2026-05-21",
            "date_added": NOW, "confirmer": "claude_code_extraction",
            "confidence": "inferred", "scope": f"sector:{sector}"
        }
    }

# ── @asteribeautysa ──────────────────────────────────────────────────────────

ASTERI_POSTS = [
    {"shortcode":"DXzb3Z2ARnY","capture_date":"2026-05-07","content_type":"video","likes":1715,
     "caption":"امتلاء أكثر بدون فيلر.. المفضل الجديد لشفاهك في الطريق",
     "visual":{"composition_style":"product launch hero — close-up lip plumping before/after reel",
       "lighting":"soft beauty studio, warm pink","color_palette_dominant":["nude pink","rose","white","gold"],
       "props_visible":["Mira Lip Shine product","lips close-up","before/after visual"],
       "setting":"studio beauty close-up","characters_visible":{"count":1},
       "text_overlays":[{"language":"bilingual","content_summary":"امتلاء أكثر بدون فيلر / Fuller without filler — hero campaign line"}],
       "notable_visual_elements":["1715 likes — peak post in account","'بدون فيلر' (no filler) is the campaign hook","bilingual copy targets Saudi + regional English audience","lip close-up texture focus — beauty standard technique"]},
     "voice":{"language":"bilingual","dialect_detected":"standard","register":"casual","tone":"confident",
              "notable_phrases":["امتلاء أكثر بدون فيلر","المفضل الجديد"],"call_to_action_present":True},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"'بدون فيلر' positions against lip filler injections — taps into Saudi beauty market trend. Bilingual copy signals Saudi-origin brand with regional aspirations. 1715 likes is exceptional for a beauty brand account of this size."},
     "patterns":[{"pattern_slug":"product_launch_reveal","confidence":"strong","notes":"Hero campaign launch — maximum engagement on 'Fuller without Filler' Mira Lip Shine"},
                  {"pattern_slug":"product_hero","confidence":"strong","notes":"Lip close-up with plumping effect — classic beauty 'before/after' format"}]},
    {"shortcode":"DXuSX02jg45","capture_date":"2026-05-06","content_type":"video","likes":1160,
     "caption":"نوع جديد من الامتلاء في الطريق / A new kind of plump is on its way",
     "visual":{"composition_style":"teaser video — product reveal with anticipation build",
       "lighting":"moody beauty studio, warm","color_palette_dominant":["deep rose","nude","gold"],
       "props_visible":["Mira Lip Shine product hint","dramatic lip visual"],
       "setting":"dark studio, dramatic beauty reveal","characters_visible":{"count":1},
       "text_overlays":[{"language":"bilingual","content_summary":"نوع جديد من الامتلاء في الطريق — teaser copy for Mira Lip Shine campaign"}],
       "notable_visual_elements":["campaign teaser — high anticipation mechanic","1160 likes on teaser = strong pre-launch momentum","bilingual Arabic/English side-by-side copy"]},
     "voice":{"language":"bilingual","dialect_detected":"standard","register":"casual","tone":"teasing",
              "notable_phrases":["نوع جديد من الامتلاء","on its way"],"call_to_action_present":False},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"Pre-launch teaser gets 1160 likes — Asteri's audience is primed for product reveals. Bilingual teaser positions brand as premium Saudi-origin beauty with international standards."},
     "patterns":[{"pattern_slug":"campaign_teaser","confidence":"strong","notes":"Pre-launch teaser with anticipation build for Mira Lip Shine"},
                  {"pattern_slug":"product_launch_reveal","confidence":"strong","notes":"'On its way' teaser mechanic — day before hero launch"}]},
    {"shortcode":"DX7KfQsFWdD","capture_date":"2026-05-04","content_type":"video","likes":185,
     "caption":"شفاه ممتلئة… بدون فيلر. نقدم لكِ مرايا ليب شاين",
     "visual":{"composition_style":"product demo — Mira Lip Shine full product introduction",
       "lighting":"warm beauty studio","color_palette_dominant":["nude pink","rose gold","cream"],
       "props_visible":["Mira Lip Shine tube","lip close-up demo","mint oil ingredient visual"],
       "setting":"clean beauty studio product presentation","characters_visible":{"count":1},
       "text_overlays":[{"language":"arabic","content_summary":"شفاه ممتلئة بدون فيلر — product intro, Mira Lip Shine with mint oil and skin-loving ingredients"}],
       "notable_visual_elements":["product name 'مرايا' (mirrors) — poetic Arabic naming","mint oil ingredient callout — clean beauty marker","full product introduction post in campaign sequence"]},
     "voice":{"language":"arabic","dialect_detected":"standard","register":"formal","tone":"confident",
              "notable_phrases":["شفاه ممتلئة بدون فيلر","مرايا ليب شاين","بمكونات محبّة للبشرة"],"call_to_action_present":True},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"'مرايا' (mirrors) as product name is poetic Arabic — intentional brand naming. 'بمكونات محبّة للبشرة' (skin-loving ingredients) = clean beauty messaging adapted for Arabic. Ingredient transparency is Asteri's brand pillar."},
     "patterns":[{"pattern_slug":"product_launch_reveal","confidence":"strong","notes":"Full product introduction with ingredient story — campaign sequence post 3"},
                  {"pattern_slug":"product_hero","confidence":"strong","notes":"Product tube close-up with lip demo — classic beauty hero shot"}]},
    {"shortcode":"DX2MM3wsjEe","capture_date":"2026-05-05","content_type":"video","likes":153,
     "caption":"شفاه ممتلئة أكثر… بدون فيلر / Fuller-looking lips… no filler needed",
     "visual":{"composition_style":"lifestyle beauty — natural lip plumping in everyday context",
       "lighting":"natural warm daylight","color_palette_dominant":["nude","warm rose","skin tone"],
       "props_visible":["Mira Lip Shine","natural makeup look","casual setting"],
       "setting":"everyday lifestyle — not studio","characters_visible":{"count":1},
       "text_overlays":[{"language":"bilingual","content_summary":"شفاه ممتلئة أكثر بدون فيلر — lifestyle application of Mira Lip Shine"}],
       "notable_visual_elements":["natural/everyday look vs studio — broader audience appeal","bilingual format same as hero post — consistent campaign","lifestyle positioning vs product-only hero"]},
     "voice":{"language":"bilingual","dialect_detected":"standard","register":"casual","tone":"natural",
              "notable_phrases":["شفاه ممتلئة أكثر بدون فيلر","no filler needed"],"call_to_action_present":True},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"Lifestyle application post after hero product launch — shows product in real life context. 'No filler needed' in English targets the same anxiety as Arabic counterpart from a different angle."},
     "patterns":[{"pattern_slug":"lifestyle_embed","confidence":"strong","notes":"Product shown in everyday lifestyle context — not just studio"},
                  {"pattern_slug":"product_hero","confidence":"moderate","notes":"Product visible but lifestyle context is the primary frame"}]},
    {"shortcode":"DYAasaYCOs-","capture_date":"2026-05-09","content_type":"carousel_slide","likes":101,
     "caption":"ثلاث درجات. ثلاث مزاجات. مرايا ليب شاين بتركيبة غنية",
     "visual":{"composition_style":"shade range carousel — 3 lip shades product lineup",
       "lighting":"clean studio beauty lighting","color_palette_dominant":["pink","rose","berry","cream"],
       "props_visible":["Mira Lip Shine x3 shades","swatches on lips","product lineup flat lay"],
       "setting":"clean white/neutral product display","characters_visible":{"count":3},
       "text_overlays":[{"language":"arabic","content_summary":"ثلاث درجات ثلاث مزاجات — 3 shades 3 moods shade carousel with shade names: بلنك / بيم / بيري"}],
       "notable_visual_elements":["carousel format shows all 3 shades sequentially","shade names in Arabic: بلنك (Blink), بيم (Beam), بيري (Berry)","3-shade rollout is classic beauty brand expansion format"]},
     "voice":{"language":"arabic","dialect_detected":"standard","register":"formal","tone":"elegant",
              "notable_phrases":["ثلاث درجات. ثلاث مزاجات","تركيبة غنية بمكونات منعشة"],"call_to_action_present":True},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"Shade launch carousel — beauty brand standard format. Shade names localized to Arabic phonetics (بلنك/بيم/بيري). 3-shade range gives brand enough variety without overcomplicating the line."},
     "patterns":[{"pattern_slug":"product_hero","confidence":"strong","notes":"Shade range carousel — classic beauty brand product line reveal"},
                  {"pattern_slug":"product_launch_reveal","confidence":"moderate","notes":"Shade extension launch — expanding the Mira Lip Shine line"}]},
    {"shortcode":"DXrthgNj8KH","capture_date":"2026-05-06","content_type":"video","likes":121,
     "caption":"انطباعات اشايا الأولى تقول كل شيء — ترطيب، إشراقة، ولمسة نهائية طبيعية",
     "visual":{"composition_style":"influencer first impression — Ashaya testing Asteri product",
       "lighting":"natural influencer-style lighting","color_palette_dominant":["skin tone","nude","warm rose"],
       "props_visible":["Asteri product","Ashaya's face","authentic reaction"],
       "setting":"natural influencer setting","characters_visible":{"count":1},
       "text_overlays":[{"language":"arabic","content_summary":"انطباعات اشايا الأولى — first impressions from Saudi influencer Ashaya, products: hydration, glow, natural finish"}],
       "notable_visual_elements":["Saudi female creator used for authentic review","'أولى' (first) = authentic unboxing/first impression format","three product benefits called out: ترطيب، إشراقة، لمسة طبيعية"]},
     "voice":{"language":"arabic","dialect_detected":"hejazi","register":"casual","tone":"genuine",
              "notable_phrases":["انطباعات اشايا الأولى","ترطيب، إشراقة، ولمسة نهائية طبيعية"],"call_to_action_present":False},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"Influencer first impression format — authenticity over polish. Saudi female creator (Ashaya) reviewing on her own terms. 'أولى' (first time) = UGC-authenticity signal even when paid collaboration."},
     "patterns":[{"pattern_slug":"influencer_review","confidence":"strong","notes":"Saudi creator first impression review — authentic UGC format"},
                  {"pattern_slug":"product_hero","confidence":"moderate","notes":"Product tested on creator in natural lighting"}]},
    {"shortcode":"DYKv3Bbqna2","capture_date":"2026-05-12","content_type":"video","likes":78,
     "caption":"شاهدوا @nani_s_makeup تضيف اللمسات الأخيرة لإطلالتها",
     "visual":{"composition_style":"get-ready-with-me — Saudi makeup artist finishing touch",
       "lighting":"warm studio/natural beauty lighting","color_palette_dominant":["rose","nude","gold"],
       "props_visible":["Asteri makeup products","brushes","professional makeup setup"],
       "setting":"makeup artist studio/vanity","characters_visible":{"count":1},
       "text_overlays":[{"language":"arabic","content_summary":"اللمسات الأخيرة — final touches with Asteri products, @nani_s_makeup collaboration"}],
       "notable_visual_elements":["professional Saudi makeup artist collaboration","'اللمسات الأخيرة' (final touches) = GRWM closing sequence","product credibility through professional artist endorsement"]},
     "voice":{"language":"arabic","dialect_detected":"hejazi","register":"casual","tone":"artistic",
              "notable_phrases":["اللمسات الأخيرة","إطلالتها"],"call_to_action_present":False},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"Professional Saudi makeup artist (@nani_s_makeup) using Asteri products = professional credibility signal. GRWM (Get Ready With Me) is one of the top-performing beauty content formats in Saudi."},
     "patterns":[{"pattern_slug":"influencer_review","confidence":"strong","notes":"Professional MUA collab — GRWM final touches format"},
                  {"pattern_slug":"product_hero","confidence":"moderate","notes":"Asteri products as the finishing tools for professional look"}]},
    {"shortcode":"DYUznfijvJi","capture_date":"2026-05-14","content_type":"video","likes":76,
     "caption":"نظرة أقرب على روتين الشفاه مع رولا — تحديد دقيق يدوم طويلاً",
     "visual":{"composition_style":"lip routine tutorial — influencer Rola demonstrating Asteri lip liner + gloss",
       "lighting":"ring light/beauty studio warm","color_palette_dominant":["nude pink","rose","skin tone"],
       "props_visible":["Extend Lip Liner","Mira Lip Shine","influencer's lips close-up"],
       "setting":"beauty influencer setup","characters_visible":{"count":1},
       "text_overlays":[{"language":"arabic","content_summary":"روتين الشفاه مع رولا — lip routine tutorial: Extend Lip Liner + Mira Lip Shine combo application"}],
       "notable_visual_elements":["product pairing tutorial: liner + gloss = full lip routine","close-up application technique = educational content","named influencer (رولا/Rola) for credibility"]},
     "voice":{"language":"arabic","dialect_detected":"hejazi","register":"casual","tone":"educational",
              "notable_phrases":["روتين الشفاه","تحديد دقيق يدوم طويلاً"],"call_to_action_present":True},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"Tutorial format with product pairing shows consumers how to use multiple Asteri products together — drives basket size. Named Saudi influencer (Rola) provides cultural credibility."},
     "patterns":[{"pattern_slug":"tutorial_how_to","confidence":"strong","notes":"Lip routine tutorial showing liner + gloss application technique"},
                  {"pattern_slug":"product_hero","confidence":"moderate","notes":"Products featured in tutorial — dual product demonstration"}]},
    {"shortcode":"DYFWg8mCvcN","capture_date":"2026-05-11","content_type":"video","likes":64,
     "caption":"هذه إشارتك لتغيري الجلوس. مرايا ليب شاين يمنحك لمعة زجاجية",
     "visual":{"composition_style":"product call-to-action — Mira Lip Shine glass-like shine demo",
       "lighting":"studio beauty, backlit shimmer","color_palette_dominant":["glossy pink","clear","rose"],
       "props_visible":["Mira Lip Shine in use","glass-like lip shine effect"],
       "setting":"studio close-up with shimmer effect","characters_visible":{"count":1},
       "text_overlays":[{"language":"arabic","content_summary":"هذه إشارتك — this is your sign to switch your lip routine, Mira Lip Shine glass shine + plumping"}],
       "notable_visual_elements":["'هذه إشارتك' (this is your sign) = classic social media CTA format","glass/glossy lip trend reference","lمعة زجاجية (glass shine) = trend-aware beauty language"]},
     "voice":{"language":"arabic","dialect_detected":"standard","register":"casual","tone":"playful",
              "notable_phrases":["هذه إشارتك لتغيري الجلوس","لمعة زجاجية"],"call_to_action_present":True},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"'هذه إشارتك' (this is your sign) is a widely used social media formula in Saudi/Arabic. 'لمعة زجاجية' (glass shine) references the glass lips beauty trend — brand is trend-aware."},
     "patterns":[{"pattern_slug":"product_hero","confidence":"strong","notes":"Glass shine lip demo — trend-referencing product showcase"},
                  {"pattern_slug":"trend_riding","confidence":"strong","notes":"'Glass lips' beauty trend referenced in product messaging"}]},
    {"shortcode":"DXw-Z0uDAxy","capture_date":"2026-05-07","content_type":"image","likes":64,
     "caption":"بتركيبة غنية بمكونات محبّة للبشرة، كوزميك كوين غلو برايمر يرطّب، ينعّم، ويمنحك قاعدة مثالية",
     "visual":{"composition_style":"product flat lay — Cosmic Queen Glow Primer on clean background",
       "lighting":"soft diffused studio lighting","color_palette_dominant":["gold","cream","white","blush"],
       "props_visible":["Cosmic Queen Glow Primer product","ingredient-inspired natural elements","clean flat lay"],
       "setting":"clean beauty product display","characters_visible":{"count":0},
       "text_overlays":[{"language":"arabic","content_summary":"كوزميك كوين غلو برايمر — Cosmic Queen Glow Primer with skin-loving ingredients, hydration + smoothing"}],
       "notable_visual_elements":["'كوزميك كوين' (Cosmic Queen) = bold English-origin brand naming in Arabic","ingredient listing in copy — clean beauty transparency","flat lay product photography — catalog style"]},
     "voice":{"language":"arabic","dialect_detected":"standard","register":"formal","tone":"informative",
              "notable_phrases":["بمكونات محبّة للبشرة","قاعدة مثالية"],"call_to_action_present":False},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"Product name 'Cosmic Queen' in Arabic transcription signals premium/aspirational branding. 'محبّة للبشرة' (skin-loving) is a Saudi beauty market phrase for clean/gentle ingredients."},
     "patterns":[{"pattern_slug":"product_hero","confidence":"strong","notes":"Primer flat lay — catalog-style product showcase with ingredient focus"},
                  {"pattern_slug":"csr_brand_story","confidence":"weak","notes":"Ingredient transparency positioning — clean beauty brand values"}]},
    {"shortcode":"DYPwuVMFY_P","capture_date":"2026-05-13","content_type":"video","likes":43,
     "caption":"مرايا ليب شاين غني بمكونات محبّة للبشرة، كوزميك كوين غلو برايمر — زيت النعناع للامتلاء الطبيعي",
     "visual":{"composition_style":"ingredient spotlight — mint oil as hero ingredient",
       "lighting":"fresh, clean, natural green tones","color_palette_dominant":["mint green","white","clear","nude"],
       "props_visible":["mint leaves","Mira Lip Shine product","clean ingredient visual"],
       "setting":"natural/ingredient-themed product shot","characters_visible":{"count":0},
       "text_overlays":[{"language":"arabic","content_summary":"زيت النعناع — mint oil ingredient featured as key plumping ingredient in Mira Lip Shine"}],
       "notable_visual_elements":["ingredient-hero format — mint shown as natural plumper","clean/natural aesthetic signals B Corp/clean beauty values","mint = freshness + natural = clean beauty positioning"]},
     "voice":{"language":"arabic","dialect_detected":"standard","register":"formal","tone":"informative",
              "notable_phrases":["زيت النعناع","امتلاء طبيعي","مكونات محبة للبشرة"],"call_to_action_present":False},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"Ingredient transparency is a key clean beauty brand signal. Asteri being Saudi-origin B Corp certified means ingredient stories are credibility pillars — 'why it works' content for informed consumers."},
     "patterns":[{"pattern_slug":"product_hero","confidence":"moderate","notes":"Ingredient hero (mint oil) rather than finished product — educational"},
                  {"pattern_slug":"csr_brand_story","confidence":"moderate","notes":"Clean ingredient story — B Corp brand values made tangible"}]},
    {"shortcode":"DYfOUt9Kxx0","capture_date":"2026-05-18","content_type":"video","likes":39,
     "caption":"إطلالة تستحق الأضواء ✨ منتجاتنا المفضلة بلمسة الفنانين المبدعين",
     "visual":{"composition_style":"artist feature — Asteri products in a creative makeup look",
       "lighting":"dramatic beauty studio","color_palette_dominant":["bold rose","metallic gold","deep nude"],
       "props_visible":["Asteri product lineup","bold artistic makeup look","creative styling"],
       "setting":"editorial beauty studio","characters_visible":{"count":1},
       "text_overlays":[{"language":"arabic","content_summary":"إطلالة تستحق الأضواء — spotlight-worthy look with Asteri products by creative artists"}],
       "notable_visual_elements":["editorial/artistic vs everyday looks","'الفنانين المبدعين' (creative artists) = brand as enabler of artistry","bold look expands brand perception beyond natural/everyday"]},
     "voice":{"language":"arabic","dialect_detected":"standard","register":"formal","tone":"aspirational",
              "notable_phrases":["إطلالة تستحق الأضواء","الفنانين المبدعين"],"call_to_action_present":False},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"Asteri expanding beyond 'clean natural look' to include bold editorial looks — shows product versatility. Saudi female creative artists as collaborators = local talent elevation narrative."},
     "patterns":[{"pattern_slug":"influencer_review","confidence":"moderate","notes":"Creative artist feature — editorial collaboration format"},
                  {"pattern_slug":"product_hero","confidence":"moderate","notes":"Asteri products in bold editorial context"}]},
    {"shortcode":"DYZ-UmmKpqy","capture_date":"2026-05-16","content_type":"video","likes":36,
     "caption":"الشفاه المثالية كما ظهرت مع شيخة 💋 محدد يدوم طويلاً مع جلوس يمنح الامتلاء",
     "visual":{"composition_style":"before/after tutorial — Shaikha showing Extend Lip Liner + Mira combo",
       "lighting":"beauty ring light, warm","color_palette_dominant":["nude rose","deep rose","skin tone"],
       "props_visible":["Extend Lip Liner","Mira Lip Shine","Shaikha's lips close-up"],
       "setting":"beauty creator setup","characters_visible":{"count":1},
       "text_overlays":[{"language":"arabic","content_summary":"الشفاه المثالية مع شيخة — perfect lips tutorial with Shaikha: Extend Lip Liner long-wear + Mira Lip Shine plumping"}],
       "notable_visual_elements":["Saudi influencer Shaikha demonstrates the complete lip routine","product pairing reinforces Asteri as full lip system","'يدوم طويلاً' (long-lasting) = durability claim for Saudi climate"]},
     "voice":{"language":"arabic","dialect_detected":"hejazi","register":"casual","tone":"educational",
              "notable_phrases":["الشفاه المثالية","محدد يدوم طويلاً","جلوس يمنح الامتلاء"],"call_to_action_present":True},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"'يدوم طويلاً' (long-lasting) is a key selling point for Saudi beauty — heat and humidity demand long-wear formulas. Shaikha as a Saudi creator provides cultural credibility for the brand's claims."},
     "patterns":[{"pattern_slug":"tutorial_how_to","confidence":"strong","notes":"Saudi influencer Shaikha demonstrates lip liner + gloss system"},
                  {"pattern_slug":"influencer_review","confidence":"strong","notes":"Named Saudi influencer credibility — Shaikha tutorial format"}]},
    {"shortcode":"DXmo780jI4d","capture_date":"2026-05-06","content_type":"video","likes":43,
     "caption":"نحت ناعم، وإشراقة طبيعية / Soft sculpt, effortless glow",
     "visual":{"composition_style":"product teaser — soft sculpt look with natural glow",
       "lighting":"natural soft light, minimal shadows","color_palette_dominant":["nude","warm blush","gold"],
       "props_visible":["Asteri face/foundation product","natural glow skin","minimalist styling"],
       "setting":"clean minimal beauty setting","characters_visible":{"count":1},
       "text_overlays":[{"language":"bilingual","content_summary":"نحت ناعم وإشراقة طبيعية / Soft sculpt effortless glow — face product campaign tease"}],
       "notable_visual_elements":["'نحت ناعم' (soft sculpt) = contouring in Arabic clean beauty language","bilingual copy for face product separate from lip campaign","natural/effortless aesthetic — anti-heavy-makeup positioning"]},
     "voice":{"language":"bilingual","dialect_detected":"standard","register":"formal","tone":"elegant",
              "notable_phrases":["نحت ناعم، وإشراقة طبيعية","soft sculpt, effortless glow"],"call_to_action_present":False},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"Bilingual elegance: Arabic and English mirror each other exactly. Clean natural glow aesthetic aligns with Asteri's B Corp brand positioning. Saudi beauty market moving toward 'no-makeup makeup' alongside bold looks."},
     "patterns":[{"pattern_slug":"product_hero","confidence":"strong","notes":"Face product natural glow hero — clean beauty aesthetic"},
                  {"pattern_slug":"campaign_teaser","confidence":"moderate","notes":"'Soft sculpt' teaser — new face product line hint"}]},
    {"shortcode":"DYkXDlQldpY","capture_date":"2026-05-20","content_type":"video","likes":22,
     "caption":"تعرفي على أساسك اليومي الجديد بثلاث درجات — بلنك: دفء ناعم / بيم: إشراقة جريئة / بيري: عمق دافئ",
     "visual":{"composition_style":"new product launch — foundation/primer 3-shade reveal",
       "lighting":"clean studio, warm","color_palette_dominant":["warm nude","golden beige","warm brown"],
       "props_visible":["3 foundation shades","swatch demos","Asteri branded packaging"],
       "setting":"clean studio product reveal","characters_visible":{"count":1},
       "text_overlays":[{"language":"arabic","content_summary":"أساسك اليومي الجديد — new daily base/foundation in 3 shades: بلنك / بيم / بيري"}],
       "notable_visual_elements":["foundation range for Saudi skin tones — warm undertones dominant","3 shade names match Mira Lip Shine shades — cross-product consistency","'أساسك اليومي' (your daily base) positioning for daily use habit formation"]},
     "voice":{"language":"arabic","dialect_detected":"standard","register":"formal","tone":"informative",
              "notable_phrases":["أساسك اليومي الجديد","دفء ناعم","إشراقة جريئة","عمق دافئ"],"call_to_action_present":True},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"Foundation shades designed for Saudi/MENA skin tones — warm undertones across all 3 shades. Shade naming consistency with Mira Lip Shine shows coordinated product line strategy. Daily base habit = recurring purchase positioning."},
     "patterns":[{"pattern_slug":"product_launch_reveal","confidence":"strong","notes":"New foundation 3-shade launch — expanding Asteri product line"},
                  {"pattern_slug":"product_hero","confidence":"strong","notes":"Foundation shade reveal with swatch demos"}]}
]

# ── @shawarmersa ──────────────────────────────────────────────────────────────

SHAWARMER_POSTS = [
    {"shortcode":"DXnevp3iK-_","capture_date":"2026-05-05","content_type":"video","likes":2072,
     "caption":"62 غرام بروتين بالدوام😎 الراهية النسخة المدخنة مافيه أقوى منها",
     "visual":{"composition_style":"protein stats hero — 62g protein in Rahiya Smoked shawarma reveal",
       "lighting":"clean product lighting with energy","color_palette_dominant":["charcoal","white","red","green"],
       "props_visible":["Al-Rahiya Smoked shawarma wrap","protein counter graphic (62g)","Shawarmer branding"],
       "setting":"product reveal with stats graphic","characters_visible":{"count":1},
       "text_overlays":[{"language":"arabic","content_summary":"62 غرام بروتين بالدوام — 62g protein at work, Rahiya Smoked is the strongest option"}],
       "notable_visual_elements":["2072 likes — standout top performer","protein count (62g) as hero number — health positioning breakthrough","'بالدوام' (at work) = commuter/busy person hook","'مافيه أقوى منها' (nothing stronger) = bold claim"]},
     "voice":{"language":"arabic","dialect_detected":"najdi","register":"casual","tone":"bold",
              "notable_phrases":["62 غرام بروتين","بالدوام","مافيه أقوى منها"],"call_to_action_present":True},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"Shawarmer's top engagement post (2072 likes) is a protein count reveal. This shows Saudi audience is highly receptive to health/nutrition positioning for traditional food. '62g protein' reframes shawarma as a fitness food — a modern positioning breakthrough."},
     "patterns":[{"pattern_slug":"product_launch_reveal","confidence":"strong","notes":"Rahiya Smoked with 62g protein stat — health-positioned product launch"},
                  {"pattern_slug":"trend_riding","confidence":"strong","notes":"Fitness/protein counting trend applied to traditional shawarma food"}]},
    {"shortcode":"DYkGdU_sZ31","capture_date":"2026-05-20","content_type":"video","likes":211,
     "caption":"POV: موظف في شاورمر. التصوير هذا لأغراض تشغيلية فقط وفريق المحتوى قرر يستخدمه",
     "visual":{"composition_style":"POV employee behind-the-scenes — funny disclaimer twist",
       "lighting":"natural restaurant lighting","color_palette_dominant":["red","white","grey"],
       "props_visible":["Shawarmer uniform", "kitchen environment","self-aware camera note"],
       "setting":"Shawarmer restaurant kitchen/ops",
       "characters_visible":{"count":2},
       "text_overlays":[{"language":"arabic","content_summary":"التصوير لأغراض تشغيلية فقط وفريق المحتوى قرر يستخدمه — 'operational footage that content team decided to use' meta-disclaimer"}],
       "notable_visual_elements":["POV format creates intimacy","self-aware meta disclaimer is the comedy — content team using 'ops footage'","employee perspective humanizes brand","211 likes — strong engagement for behind-the-scenes"]},
     "voice":{"language":"arabic","dialect_detected":"najdi","register":"casual","tone":"playful",
              "notable_phrases":["POV: موظف في شاورمر","لأغراض تشغيلية فقط","فريق المحتوى قرر يستخدمه"],"call_to_action_present":False},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"The meta-disclaimer ('operational footage, content team used it') is a sophisticated humor move — self-aware brand voice. POV employee format is trending in Saudi social media. This type of personality-driven content differentiates Shawarmer from generic F&B brands."},
     "patterns":[{"pattern_slug":"behind_the_scenes","confidence":"strong","notes":"POV employee content with self-aware meta-comedy twist"},
                  {"pattern_slug":"brand_personality","confidence":"strong","notes":"Witty disclaimer shows brand has a distinct voice and personality"}]},
    {"shortcode":"DXcDGDDjCtJ","capture_date":"2026-04-30","content_type":"video","likes":185,
     "caption":"كيف نعرف الزيت صالح ولا لا؟ #إعرف_شاورمتك",
     "visual":{"composition_style":"transparency video — oil quality testing in kitchen",
       "lighting":"kitchen operational lighting","color_palette_dominant":["amber","white","red"],
       "props_visible":["cooking oil test kit","Shawarmer kitchen","quality check procedure"],
       "setting":"Shawarmer kitchen, operational quality check",
       "characters_visible":{"count":1},
       "text_overlays":[{"language":"arabic","content_summary":"كيف نعرف الزيت صالح ولا لا؟ #إعرف_شاورمتك — how we test if oil is still good, Know Your Shawarma series"}],
       "notable_visual_elements":["#إعرف_شاورمتك series = 'Know Your Shawarma' transparency campaign","oil quality testing = food safety transparency","consumer education = trust building","185 likes — strong performance for 'boring' operational content"]},
     "voice":{"language":"arabic","dialect_detected":"najdi","register":"casual","tone":"informative",
              "notable_phrases":["كيف نعرف الزيت صالح ولا لا؟","#إعرف_شاورمتك"],"call_to_action_present":False},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"#إعرف_شاورمتك (Know Your Shawarma) is Shawarmer's transparency content series. Showing oil quality testing builds trust by addressing a common fast food concern. This content answers questions consumers have but never ask."},
     "patterns":[{"pattern_slug":"transparency_trust_content","confidence":"strong","notes":"Oil quality testing shown publicly — #إعرف_شاورمتك series"},
                  {"pattern_slug":"behind_the_scenes","confidence":"strong","notes":"Kitchen quality control as brand trust building content"}]},
    {"shortcode":"DXXCVvUDIta","capture_date":"2026-05-05","content_type":"video","likes":145,
     "caption":"نصيحتي وحده من بداية الشهر! نصيحة جربوها 🌯🔥",
     "visual":{"composition_style":"Ramadan tip video — monthly advice for shawarma nutrition",
       "lighting":"warm, lifestyle","color_palette_dominant":["red","warm beige","white"],
       "props_visible":["Shawarmer Rahiya wrap","nutritional context","Ramadan setting cue"],
       "setting":"lifestyle setting, Ramadan context","characters_visible":{"count":1},
       "text_overlays":[{"language":"arabic","content_summary":"نصيحتي وحده من بداية الشهر — my one advice from the start of the month, Ramadan nutrition tip"}],
       "notable_visual_elements":["Ramadan context implied ('الشهر' = the holy month)","personal advice format = credibility/authenticity","product framed as Ramadan nutrition solution"]},
     "voice":{"language":"arabic","dialect_detected":"najdi","register":"casual","tone":"friendly",
              "notable_phrases":["نصيحتي وحده من بداية الشهر","جربوها"],"call_to_action_present":True},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":"Ramadan 2026",
       "hospitality_cues":["Ramadan iftar tradition"],"heritage_vs_modern":"modern",
       "free_notes":"'الشهر' (the month) refers to Ramadan without saying it — shorthand understood by all Saudi audience. Framing shawarma as Ramadan nutrition tip is clever — connects protein positioning to iftar context."},
     "patterns":[{"pattern_slug":"occasion_peg","confidence":"moderate","notes":"Ramadan context implied — shawarma as iftar nutrition advice"},
                  {"pattern_slug":"lifestyle_embed","confidence":"strong","notes":"Personal advice format makes product recommendation feel genuine"}]},
    {"shortcode":"DXuUvIljNhq","capture_date":"2026-05-07","content_type":"video","likes":145,
     "caption":"الخضروات عندنا لاتشيل همها 🥬 #اعرف_شاورمتك",
     "visual":{"composition_style":"transparency video — fresh vegetable sourcing and prep",
       "lighting":"fresh kitchen lighting","color_palette_dominant":["green","white","red"],
       "props_visible":["fresh vegetables being prepped","Shawarmer kitchen","clean cutting board"],
       "setting":"Shawarmer kitchen prep area, fresh ingredients visible","characters_visible":{"count":1},
       "text_overlays":[{"language":"arabic","content_summary":"الخضروات عندنا لاتشيل همها — our vegetables, don't worry about them (fresh + high quality)"}],
       "notable_visual_elements":["'لاتشيل همها' (don't worry about them) — dismisses food safety concerns with confidence","fresh green vegetables = visual freshness signal","#إعرف_شاورمتك series continuation — vegetables episode"]},
     "voice":{"language":"arabic","dialect_detected":"najdi","register":"casual","tone":"reassuring",
              "notable_phrases":["لاتشيل همها","الخضروات عندنا"],"call_to_action_present":False},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":["fresh ingredients = hospitality quality standard"],"heritage_vs_modern":"modern",
       "free_notes":"'لاتشيل همها' (don't worry about them) is Najdi colloquial for reassurance. Showing vegetables directly addresses the 'are fast food vegetables fresh?' consumer concern. Trust through radical transparency."},
     "patterns":[{"pattern_slug":"transparency_trust_content","confidence":"strong","notes":"Fresh vegetable sourcing shown — #إعرف_شاورمتك vegetables episode"},
                  {"pattern_slug":"behind_the_scenes","confidence":"strong","notes":"Kitchen prep visibility as consumer reassurance strategy"}]},
    {"shortcode":"DYSp_tzxsMp","capture_date":"2026-05-14","content_type":"video","likes":126,
     "caption":"روتين النظافة عند موظفيننا #إعرف_شاورمتك",
     "visual":{"composition_style":"cleanliness routine video — staff hygiene procedures shown",
       "lighting":"operational kitchen lighting","color_palette_dominant":["white","red","grey"],
       "props_visible":["staff in uniform","cleaning supplies","hygiene protocol visuals"],
       "setting":"Shawarmer kitchen/service area during cleaning routine","characters_visible":{"count":2},
       "text_overlays":[{"language":"arabic","content_summary":"روتين النظافة عند موظفيننا — staff cleaning routine #إعرف_شاورمتك"}],
       "notable_visual_elements":["cleaning routine = most direct trust signal possible","staff following protocol = systematic quality assurance","#إعرف_شاورمتك hygiene episode — addresses core fast food concern"]},
     "voice":{"language":"arabic","dialect_detected":"najdi","register":"casual","tone":"matter-of-fact",
              "notable_phrases":["روتين النظافة","عند موظفيننا"],"call_to_action_present":False},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":["cleanliness = Islamic hygiene standard (نظافة من الإيمان)"],"heritage_vs_modern":"modern",
       "free_notes":"Cleanliness is deeply valued in Saudi/Islamic culture ('النظافة من الإيمان' — cleanliness is part of faith). Showing cleaning routines resonates deeply. Shawarmer showing this publicly is a high-trust move."},
     "patterns":[{"pattern_slug":"transparency_trust_content","confidence":"strong","notes":"Staff cleaning routine — #إعرف_شاورمتك hygiene episode"},
                  {"pattern_slug":"behind_the_scenes","confidence":"strong","notes":"Operational hygiene procedure shown publicly — maximum trust signal"}]},
    {"shortcode":"DYFZ-qSMXoY","capture_date":"2026-05-11","content_type":"video","likes":136,
     "caption":"62 غرام بروتين بشاورما وحدة💪🏻",
     "visual":{"composition_style":"protein fact continuation — 62g protein single shawarma",
       "lighting":"clean product lighting","color_palette_dominant":["red","charcoal","white"],
       "props_visible":["shawarma wrap with protein badge","62g graphic","Shawarmer branding"],
       "setting":"product with stats, clean background","characters_visible":{"count":0},
       "text_overlays":[{"language":"arabic","content_summary":"62 غرام بروتين بشاورما وحدة — 62g protein in ONE shawarma"}],
       "notable_visual_elements":["'وحدة' (one) = single item protein emphasis","protein count campaign continuation","product without person — stat-only format"]},
     "voice":{"language":"arabic","dialect_detected":"najdi","register":"casual","tone":"confident",
              "notable_phrases":["62 غرام بروتين","بشاورما وحدة"],"call_to_action_present":True},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"Protein count campaign using consistent 62g number across multiple posts — repetition creates recall. 'بشاورما وحدة' (in one shawarma) emphasizes single-item sufficiency for fitness goals."},
     "patterns":[{"pattern_slug":"product_hero","confidence":"moderate","notes":"Product with protein stat graphic — nutrition-forward product hero"},
                  {"pattern_slug":"trend_riding","confidence":"strong","notes":"Protein content trend — health positioning for traditional food"}]},
    {"shortcode":"DYCL792sEZg","capture_date":"2026-05-09","content_type":"video","likes":118,
     "caption":"بهالحر☀️ ودكم تعرفون كيف نخزن ونحافظ على أسياخ الشاورما؟ #إعرف_شاورمتك",
     "visual":{"composition_style":"summer heat transparency — shawarma spit storage in Saudi heat",
       "lighting":"warm, slightly harsh — summer heat atmosphere","color_palette_dominant":["charcoal","warm red","white"],
       "props_visible":["shawarma spits in cold storage","refrigeration unit","Shawarmer kitchen"],
       "setting":"Shawarmer cold storage/kitchen during summer","characters_visible":{"count":1},
       "text_overlays":[{"language":"arabic","content_summary":"بهالحر — in this heat, how we store and preserve shawarma spits (cold chain transparency)"}],
       "notable_visual_elements":["'بهالحر' (in this heat) = Riyadh summer acknowledgment — relatable","cold chain storage shown = food safety assurance","summer timing makes food safety top of mind for Saudi consumer"]},
     "voice":{"language":"arabic","dialect_detected":"najdi","register":"casual","tone":"informative",
              "notable_phrases":["بهالحر", "كيف نخزن ونحافظ على أسياخ الشاورما"],"call_to_action_present":False},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":"Saudi summer (May-September)",
       "hospitality_cues":["cold storage during Riyadh heat = food safety excellence"],"heritage_vs_modern":"modern",
       "free_notes":"'بهالحر' (in this heat) is a shared Saudi summer experience — Riyadh heat is extreme. Showing cold chain storage during summer addresses the most contextually relevant food safety concern. Season-aware content."},
     "patterns":[{"pattern_slug":"transparency_trust_content","confidence":"strong","notes":"Summer cold chain storage shown — seasonal food safety reassurance"},
                  {"pattern_slug":"occasion_peg","confidence":"moderate","notes":"Saudi summer heat as contextual occasion hook for food storage content"}]},
    {"shortcode":"DX7L6hhxl7X","capture_date":"2026-05-04","content_type":"video","likes":75,
     "caption":"عشان خاطر الشاورمرية مددنا فترة الراهية النسخة المدخنة، آخر فرصة للي ما جربها",
     "visual":{"composition_style":"campaign extension announcement — Rahiya Smoked extended for fans",
       "lighting":"warm product lighting","color_palette_dominant":["charcoal smoke","red","white"],
       "props_visible":["Rahiya Smoked wrap","smoky visual effect","Shawarmer branding"],
       "setting":"branded product environment","characters_visible":{"count":0},
       "text_overlays":[{"language":"arabic","content_summary":"عشان خاطر الشاورمرية — for the sake of Shawarmer fans, extended Rahiya Smoked period, last chance"}],
       "notable_visual_elements":["'الشاورمرية' (Shawarmer fans/loyalists) — brand naming its fanbase","extension for fans = listening-to-community signal","'آخر فرصة' (last chance) = FOMO urgency"]},
     "voice":{"language":"arabic","dialect_detected":"najdi","register":"casual","tone":"warm",
              "notable_phrases":["عشان خاطر الشاورمرية","آخر فرصة للي ما جربها"],"call_to_action_present":True},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"'الشاورمرية' (Shawarmer fans) = brand has named its community. 'عشان خاطركم' (for your sake) is a Saudi hospitality phrase adapted for brand-fan relationship. Extension 'because you asked' is a powerful community-responsive signal."},
     "patterns":[{"pattern_slug":"returning_fan_favourite","confidence":"strong","notes":"Rahiya Smoked extension 'for the fans' — community-responsive campaign extension"},
                  {"pattern_slug":"price_offer_graphic","confidence":"weak","notes":"Last chance urgency — limited time mechanic"}]},
    {"shortcode":"DX3GgvrowaY","capture_date":"2026-05-03","content_type":"video","likes":51,
     "caption":"جديييد انبسطوا مع بيبسي🔥 @pepsi_saudi",
     "visual":{"composition_style":"collab teaser — new Pepsi x Shawarmer partnership announcement",
       "lighting":"vibrant, collab energy","color_palette_dominant":["red","blue","white"],
       "props_visible":["Pepsi branding","Shawarmer branding","collab visual"],
       "setting":"co-branded teaser graphic","characters_visible":{"count":0},
       "text_overlays":[{"language":"arabic","content_summary":"جديييد انبسطوا مع بيبسي — new (stretched for excitement), enjoy with Pepsi, Pepsi x Shawarmer collab"}],
       "notable_visual_elements":["'جديييد' (new spelled with extended ي) = excitement stretching","Pepsi collab = brand elevation through beverage partnership","multiple exclamation points + fire emoji = Saudi social media hype format"]},
     "voice":{"language":"arabic","dialect_detected":"najdi","register":"casual","tone":"excited",
              "notable_phrases":["جديييد انبسطوا","مع بيبسي"],"call_to_action_present":False},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"Stretching Arabic words for emphasis ('جديييد' instead of 'جديد') is a common Saudi social media expression of excitement. Pepsi collab is a brand statement — Shawarmer positioning alongside an iconic global brand."},
     "patterns":[{"pattern_slug":"collab_campaign_reveal","confidence":"strong","notes":"Pepsi x Shawarmer partnership announcement teaser"},
                  {"pattern_slug":"campaign_teaser","confidence":"strong","notes":"'جديد' teaser before full campaign reveal"}]},
    {"shortcode":"DX95GVeuMyp","capture_date":"2026-05-03","content_type":"video","likes":49,
     "caption":"انتظرونا مع @pepsi_saudi 👀⚽️",
     "visual":{"composition_style":"anticipation teaser — Pepsi x Shawarmer + football hint",
       "lighting":"dynamic, sports energy","color_palette_dominant":["red","blue","white"],
       "props_visible":["Pepsi visual hint","football/soccer element","Shawarmer teaser"],
       "setting":"sports/collab teaser environment","characters_visible":{"count":0},
       "text_overlays":[{"language":"arabic","content_summary":"انتظرونا مع بيبسي — wait for us with Pepsi, football emoji = Champions League hint"}],
       "notable_visual_elements":["eye emoji (👀) = Saudi social 'stay tuned' shorthand","football emoji (⚽️) = Champions League activation hint","bare/minimal copy = maximum intrigue"]},
     "voice":{"language":"arabic","dialect_detected":"najdi","register":"casual","tone":"teasing",
              "notable_phrases":["انتظرونا","مع بيبسي"],"call_to_action_present":False},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":"Champions League season",
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"'انتظرونا' (wait for us) is a teaser formula used widely in Saudi brand social media. Eye emoji + football = Saudi audience immediately understands Champions League collab is coming. Minimal copy = maximum speculation."},
     "patterns":[{"pattern_slug":"campaign_teaser","confidence":"strong","notes":"Ultra-minimal Pepsi + football teaser — Champions League collab hint"},
                  {"pattern_slug":"sports_passion_peg","confidence":"moderate","notes":"Football emoji tie-in with Champions League season"}]},
    {"shortcode":"DXbW6HNDG_b","capture_date":"2026-04-30","content_type":"video","likes":75,
     "caption":"صحيح اللي قريته .. 62 غرام بروتين",
     "visual":{"composition_style":"confirmation post — 62g protein validation with reaction format",
       "lighting":"product + reaction lighting","color_palette_dominant":["red","white","charcoal"],
       "props_visible":["Rahiya Smoked product","62g protein graphic","confirmation visual"],
       "setting":"product with confirmation reaction","characters_visible":{"count":1},
       "text_overlays":[{"language":"arabic","content_summary":"صحيح اللي قريته — yes, what you read is correct, 62g protein (validation post)"}],
       "notable_visual_elements":["'صحيح اللي قريته' (yes, what you read is correct) = validates and amplifies the claim","response to skepticism mechanic — 'yes it's real'","confidence in claim is itself the message"]},
     "voice":{"language":"arabic","dialect_detected":"najdi","register":"casual","tone":"confident",
              "notable_phrases":["صحيح اللي قريته","62 غرام بروتين"],"call_to_action_present":True},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"'صحيح اللي قريته' is a classic Saudi social media format for surprising/impressive claims. Implying the audience might not believe 62g protein — and confirming it — creates a scroll-stopping moment. Confidence as persuasion."},
     "patterns":[{"pattern_slug":"product_hero","confidence":"moderate","notes":"62g protein confirmation post — same claim, different format"},
                  {"pattern_slug":"trend_riding","confidence":"strong","notes":"Protein counting trend — response to audience disbelief creates secondary engagement"}]},
    {"shortcode":"DXZSBKwjNwr","capture_date":"2026-04-30","content_type":"image","likes":61,
     "caption":"بدون مانكثر كلام ... 62غرام بروتين",
     "visual":{"composition_style":"minimal stat graphic — 62g protein statement image",
       "lighting":"clean graphic","color_palette_dominant":["charcoal","white","red"],
       "props_visible":["62g protein number graphic","Shawarmer logo","minimal design"],
       "setting":"minimal branded graphic","characters_visible":{"count":0},
       "text_overlays":[{"language":"arabic","content_summary":"بدون مانكثر كلام — without saying much, 62g protein (minimal copy maximum impact)"}],
       "notable_visual_elements":["'بدون مانكثر كلام' (without saying much) — the copy contradicts itself humorously","minimal design = confidence in the number alone","pure stat graphic — number as hero"]},
     "voice":{"language":"arabic","dialect_detected":"najdi","register":"casual","tone":"playful",
              "notable_phrases":["بدون مانكثر كلام","62غرام بروتين"],"call_to_action_present":False},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"'بدون مانكثر كلام' (without saying much) is a humorous Saudi phrase — the statement says the opposite of what it does (it IS saying a lot by saying little). Minimal design amplifies the number. The stat speaks for itself."},
     "patterns":[{"pattern_slug":"product_hero","confidence":"moderate","notes":"Protein stat as hero — minimal graphic, maximum confidence"},
                  {"pattern_slug":"brand_personality","confidence":"strong","notes":"Self-aware humor ('without saying much') shows distinct brand voice"}]},
    {"shortcode":"DYkeED3uAXg","capture_date":"2026-05-20","content_type":"image","likes":24,
     "caption":"ما تحبين الثوم؟ اطلبيها بدون ثوم. بدلي الثوم بشاورمتك اللي تحبينها بـ شطة وإلا كاتشب",
     "visual":{"composition_style":"customization offer — garlic-free shawarma option",
       "lighting":"clean product","color_palette_dominant":["red","cream","white"],
       "props_visible":["shawarma options","garlic-free visual indicator","customization graphic"],
       "setting":"product customization communication graphic","characters_visible":{"count":0},
       "text_overlays":[{"language":"arabic","content_summary":"اطلبيها بدون ثوم — order it without garlic, replace with hot sauce or ketchup (female addressed)"}],
       "notable_visual_elements":["feminine address (تحبين / اطلبيها) — targeting female customers","garlic avoidance is a common Saudi food preference","customization = hospitality value (order it YOUR way)"]},
     "voice":{"language":"arabic","dialect_detected":"najdi","register":"casual","tone":"friendly",
              "notable_phrases":["ما تحبين الثوم؟","اطلبيها بدون ثوم"],"call_to_action_present":True},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":None,
       "hospitality_cues":["customization = food hospitality — guest gets it their way"],"heritage_vs_modern":"modern",
       "free_notes":"Feminine address (ي suffix) signals this post targets female customers specifically. Garlic avoidance is common in Saudi (especially before work/social events). Customization messaging resonates with Saudi hospitality values — 'your way'."},
     "patterns":[{"pattern_slug":"product_hero","confidence":"weak","notes":"Product customization options — hospitality-framed choice"},
                  {"pattern_slug":"lifestyle_embed","confidence":"moderate","notes":"Garlic avoidance preference — relatable everyday consumer insight"}]},
    {"shortcode":"DYl6VYqMRLN","capture_date":"2026-05-21","content_type":"video","likes":16,
     "caption":"كيييف المشاعر لمباراة اليوم؟👀 #النصر_ضمك",
     "visual":{"composition_style":"football engagement — emotion check for Al-Nassr vs Damak match",
       "lighting":"sports energy visual","color_palette_dominant":["gold","blue","white","red"],
       "props_visible":["football match reference","Shawarmer branding hint"],
       "setting":"sports match day engagement post","characters_visible":{"count":0},
       "text_overlays":[{"language":"arabic","content_summary":"كيييف المشاعر لمباراة اليوم؟ — how are the feelings for today's match? Al-Nassr vs Damak"}],
       "notable_visual_elements":["'كيييف المشاعر' (stretched كيف) = Saudi excitement/anticipation expression","#النصر_ضمك = specific Saudi football match tag","Al-Nassr = Ronaldo's club — highest visibility Saudi football","lowest engagement (16 likes) — shows match-day posts have limited reach vs product content"]},
     "voice":{"language":"arabic","dialect_detected":"najdi","register":"casual","tone":"excited",
              "notable_phrases":["كيييف المشاعر","لمباراة اليوم؟"],"call_to_action_present":False},
     "cultural_notes":{"regional_orientation_detected":"general_saudi","occasion_relevance":"Saudi Pro League — Al-Nassr vs Al-Damak match",
       "hospitality_cues":[],"heritage_vs_modern":"modern",
       "free_notes":"Al-Nassr (Ronaldo's club) is the highest-profile Saudi club. Match-day engagement posts are common but this one only got 16 likes — showing football real-time posts underperform vs product/transparency content for Shawarmer. Interesting anti-pattern vs Herfy's football content."},
     "patterns":[{"pattern_slug":"sports_passion_peg","confidence":"strong","notes":"Al-Nassr match day engagement — Saudi football passion hook"},
                  {"pattern_slug":"occasion_peg","confidence":"moderate","notes":"Specific Saudi Pro League match occasion"}]}
]


def main():
    beauty_dir = REPO / "11_who_to_learn_from" / "observations" / "beauty"
    fab_dir = REPO / "11_who_to_learn_from" / "observations" / "f_and_b"
    beauty_dir.mkdir(parents=True, exist_ok=True)
    fab_dir.mkdir(parents=True, exist_ok=True)

    for posts, handle_norm, account_ulid, sector, obs_dir, acc_name in [
        (ASTERI_POSTS, "OGZ-BEAUTY-Reference-001", "01KS5PZ5T5J535JPWGJER6R2D1", "beauty", beauty_dir, "asteribeautysa"),
        (SHAWARMER_POSTS, "OGZ-F-AND-B-Reference-009", "01KS5PZ5T5YSN7GNCCVJ7AZ85T", "f_and_b", fab_dir, "shawarmersa"),
    ]:
        written = 0
        for post in posts:
            obs = build_obs(post, handle_norm, account_ulid, sector, obs_dir)
            (obs_dir / f"{obs['observation_ulid']}.json").write_text(json.dumps(obs, ensure_ascii=False, indent=2))
            written += 1
        print(f"  @{acc_name}: {written} obs → {obs_dir.name}/")

    print("\nDone.")

if __name__ == "__main__":
    main()
